import * as fs from "fs";
import * as path from "path";
import type { GeneratedDocument } from "../generator/index.js";
import type { CodepliantConfig } from "../config.js";

/**
 * Converts a document filename to a wiki-friendly page name.
 * E.g. "PRIVACY_POLICY.md" -> "Privacy-Policy"
 */
function toWikiPageName(filename: string): string {
  return filename
    .replace(/\.md$/i, "")
    .replace(/_/g, "-")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("-");
}

/**
 * Generates the _Sidebar.md navigation file for a GitHub Wiki.
 */
function generateSidebar(
  docs: GeneratedDocument[],
  config?: CodepliantConfig
): string {
  const companyName = config?.companyName || "Compliance Documents";
  const lines: string[] = [];

  lines.push(`### ${companyName}`);
  lines.push("");
  lines.push("**Compliance Documents**");
  lines.push("");

  for (const doc of docs) {
    const pageName = toWikiPageName(doc.filename);
    lines.push(`- [[${doc.name}|${pageName}]]`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `_Generated by [Codepliant](https://github.com/joechensmartz/codepliant) on ${new Date().toISOString().split("T")[0]}_`
  );

  return lines.join("\n");
}

/**
 * Adds a wiki header to the document content.
 * Strips the first H1 heading if present (wiki uses the page title instead).
 */
function prepareWikiContent(doc: GeneratedDocument): string {
  let content = doc.content;

  // Remove leading H1 — the wiki page title serves as the heading
  const lines = content.split("\n");
  if (lines.length > 0 && /^# /.test(lines[0])) {
    lines.shift();
    // Also remove the blank line that typically follows the heading
    if (lines.length > 0 && lines[0].trim() === "") {
      lines.shift();
    }
    content = lines.join("\n");
  }

  return content;
}

/**
 * Generates the Home.md page for the wiki.
 */
function generateHomePage(
  docs: GeneratedDocument[],
  config?: CodepliantConfig
): string {
  const companyName = config?.companyName || "Our";
  const lines: string[] = [];

  lines.push(`# ${companyName} Compliance Documents`);
  lines.push("");
  lines.push(
    "This wiki contains all compliance and legal documents generated from our codebase."
  );
  lines.push("");
  lines.push("## Documents");
  lines.push("");

  for (const doc of docs) {
    const pageName = toWikiPageName(doc.filename);
    lines.push(`- **[[${doc.name}|${pageName}]]**`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `> These documents were auto-generated by [Codepliant](https://github.com/joechensmartz/codepliant) on ${new Date().toISOString().split("T")[0]}. Review and customize them for your specific legal requirements.`
  );

  return lines.join("\n");
}

/**
 * Writes documents as GitHub Wiki-compatible pages.
 *
 * Output structure:
 *   wiki/
 *     Home.md
 *     _Sidebar.md
 *     Privacy-Policy.md
 *     Terms-Of-Service.md
 *     ...
 *
 * Ready to push to <project>.wiki.git.
 */
export function writeGithubWiki(
  docs: GeneratedDocument[],
  outputDir: string,
  config?: CodepliantConfig
): string[] {
  const wikiDir = path.join(outputDir, "wiki");
  if (!fs.existsSync(wikiDir)) {
    fs.mkdirSync(wikiDir, { recursive: true });
  }

  const writtenFiles: string[] = [];

  // Write Home.md
  const homePath = path.join(wikiDir, "Home.md");
  fs.writeFileSync(homePath, generateHomePage(docs, config), "utf-8");
  writtenFiles.push(homePath);

  // Write _Sidebar.md
  const sidebarPath = path.join(wikiDir, "_Sidebar.md");
  fs.writeFileSync(sidebarPath, generateSidebar(docs, config), "utf-8");
  writtenFiles.push(sidebarPath);

  // Write individual document pages
  for (const doc of docs) {
    const pageName = toWikiPageName(doc.filename);
    const pagePath = path.join(wikiDir, `${pageName}.md`);
    const content = prepareWikiContent(doc);
    fs.writeFileSync(pagePath, content, "utf-8");
    writtenFiles.push(pagePath);
  }

  return writtenFiles;
}
