import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates CONSENT_RECORD_TEMPLATE.md — a template for logging user consent
 * events in compliance with GDPR Article 7 evidence requirements.
 *
 * Fields: user ID, timestamp, consent type, IP, method, version.
 *
 * Always generated when services are detected (any organisation processing
 * personal data on the basis of consent needs to demonstrate valid consent).
 */
export function generateConsentRecordTemplate(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const website = ctx?.website || "[https://yoursite.com]";
  const date = new Date().toISOString().split("T")[0];

  const hasAnalytics = scan.services.some((s) => s.category === "analytics");
  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasMarketing = scan.services.some(
    (s) => s.category === "analytics" || s.category === "advertising",
  );
  const hasPayment = scan.services.some((s) => s.category === "payment");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Consent Record Template");
  lines.push("");
  lines.push(`> **${company}** — GDPR Art. 7 Consent Evidence Records`);
  lines.push(">");
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(">");
  lines.push("> Generated by [Codepliant](https://github.com/codepliant/codepliant)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Purpose ──────────────────────────────────────────────────────────
  lines.push("## 1. Purpose");
  lines.push("");
  lines.push(
    `This document defines the consent record format used by ${company} to demonstrate that valid consent was obtained from data subjects, as required by GDPR Article 7(1): "Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented to the processing of his or her personal data."`,
  );
  lines.push("");
  lines.push("Every consent event (grant, withdrawal, modification) must be logged using this template and stored for the duration of the processing activity plus the applicable retention period.");
  lines.push("");

  // ── 2. Consent Record Fields ────────────────────────────────────────────
  lines.push("## 2. Consent Record Fields");
  lines.push("");
  lines.push("Each consent record **must** contain the following fields:");
  lines.push("");
  lines.push("| Field | Type | Required | Description |");
  lines.push("|-------|------|----------|-------------|");
  lines.push("| `consent_id` | UUID | Yes | Unique identifier for this consent record |");
  lines.push("| `user_id` | String | Yes | Internal user identifier (anonymised where possible) |");
  lines.push("| `timestamp` | ISO 8601 | Yes | Exact date and time consent was recorded (UTC) |");
  lines.push("| `consent_type` | Enum | Yes | Category of consent (see Section 3) |");
  lines.push("| `consent_action` | Enum | Yes | `granted`, `withdrawn`, `modified`, `expired` |");
  lines.push("| `ip_address` | String | Yes | IP address at time of consent (for geo-verification) |");
  lines.push("| `user_agent` | String | Yes | Browser/device user agent string |");
  lines.push("| `method` | Enum | Yes | How consent was collected (see Section 4) |");
  lines.push("| `policy_version` | String | Yes | Version of the privacy/cookie policy shown at consent time |");
  lines.push("| `consent_text` | String | Yes | Exact text/prompt presented to the user |");
  lines.push("| `language` | ISO 639-1 | Yes | Language of the consent prompt |");
  lines.push("| `expiry_date` | ISO 8601 | No | When this consent expires (if applicable) |");
  lines.push("| `parent_consent_id` | UUID | No | Links to prior consent record if modified/renewed |");
  lines.push("| `source_url` | URL | No | Page URL where consent was collected |");
  lines.push("| `geo_location` | String | No | Country/region derived from IP (for jurisdiction) |");
  lines.push("");

  // ── 3. Consent Types ────────────────────────────────────────────────────
  lines.push("## 3. Consent Types");
  lines.push("");
  lines.push("Define all consent types applicable to your processing activities:");
  lines.push("");
  lines.push("| Consent Type | Description | Lawful Basis |");
  lines.push("|-------------|-------------|--------------|");
  lines.push("| `essential` | Essential service functionality | Not consent-based (legitimate interest/contract) |");
  if (hasAnalytics) {
    lines.push("| `analytics` | Website/app analytics and usage tracking | Consent (Art. 6(1)(a)) |");
  }
  if (hasMarketing) {
    lines.push("| `marketing` | Marketing emails, newsletters, promotions | Consent (Art. 6(1)(a)) |");
    lines.push("| `advertising` | Targeted advertising and ad personalisation | Consent (Art. 6(1)(a)) |");
  }
  lines.push("| `third_party` | Sharing data with third-party processors | Consent (Art. 6(1)(a)) |");
  if (hasAI) {
    lines.push("| `ai_processing` | AI/ML model training or automated decision-making | Explicit consent (Art. 9(2)(a) / Art. 22(2)(c)) |");
  }
  if (hasPayment) {
    lines.push("| `payment` | Storing payment details for future transactions | Consent (Art. 6(1)(a)) |");
  }
  lines.push("| `communication` | Contact via specific channels (email, SMS, push) | Consent (Art. 6(1)(a)) |");
  lines.push("| `profiling` | User profiling for personalised experiences | Consent (Art. 6(1)(a)) |");
  lines.push("");

  // ── 4. Collection Methods ───────────────────────────────────────────────
  lines.push("## 4. Collection Methods");
  lines.push("");
  lines.push("| Method | Description | Evidence Stored |");
  lines.push("|--------|-------------|-----------------|");
  lines.push("| `web_form` | Checkbox or toggle on website/app | Screenshot hash, form version |");
  lines.push("| `cookie_banner` | Cookie consent management platform | CMP record ID, banner version |");
  lines.push("| `email_optin` | Double opt-in email confirmation | Confirmation email ID, click timestamp |");
  lines.push("| `api` | Consent granted via API call | API request log, auth token |");
  lines.push("| `verbal` | Verbal consent (phone/in-person) | Call recording ID, witness name |");
  lines.push("| `written` | Physical or digital signed form | Document ID, signature hash |");
  lines.push("| `sso` | Consent during SSO/OAuth flow | OAuth scope, provider record |");
  lines.push("");

  // ── 5. Example Records ─────────────────────────────────────────────────
  lines.push("## 5. Example Consent Records");
  lines.push("");
  lines.push("### 5.1 Consent Granted");
  lines.push("");
  lines.push("```json");
  lines.push("{");
  lines.push('  "consent_id": "550e8400-e29b-41d4-a716-446655440000",');
  lines.push('  "user_id": "usr_a1b2c3d4",');
  lines.push(`  "timestamp": "${date}T14:30:00Z",`);
  lines.push('  "consent_type": "analytics",');
  lines.push('  "consent_action": "granted",');
  lines.push('  "ip_address": "203.0.113.42",');
  lines.push('  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)...",');
  lines.push('  "method": "cookie_banner",');
  lines.push('  "policy_version": "2.1.0",');
  lines.push('  "consent_text": "We use analytics cookies to understand how you use our site. You can change your preferences at any time.",');
  lines.push('  "language": "en",');
  lines.push(`  "expiry_date": "${new Date(Date.now() + 365 * 86400000).toISOString().split("T")[0]}T00:00:00Z",`);
  lines.push(`  "source_url": "${website}/signup",`);
  lines.push('  "geo_location": "DE"');
  lines.push("}");
  lines.push("```");
  lines.push("");

  lines.push("### 5.2 Consent Withdrawn");
  lines.push("");
  lines.push("```json");
  lines.push("{");
  lines.push('  "consent_id": "660e8400-e29b-41d4-a716-446655440001",');
  lines.push('  "user_id": "usr_a1b2c3d4",');
  lines.push(`  "timestamp": "${date}T16:45:00Z",`);
  lines.push('  "consent_type": "analytics",');
  lines.push('  "consent_action": "withdrawn",');
  lines.push('  "ip_address": "203.0.113.42",');
  lines.push('  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)...",');
  lines.push('  "method": "web_form",');
  lines.push('  "policy_version": "2.1.0",');
  lines.push('  "consent_text": "You have withdrawn your consent for analytics cookies.",');
  lines.push('  "language": "en",');
  lines.push('  "parent_consent_id": "550e8400-e29b-41d4-a716-446655440000",');
  lines.push(`  "source_url": "${website}/settings/privacy",`);
  lines.push('  "geo_location": "DE"');
  lines.push("}");
  lines.push("```");
  lines.push("");

  // ── 6. GDPR Art. 7 Compliance Checklist ─────────────────────────────────
  lines.push("## 6. GDPR Article 7 Compliance Checklist");
  lines.push("");
  lines.push("Ensure each consent record meets these requirements:");
  lines.push("");
  lines.push("- [ ] **Demonstrable (Art. 7(1))** — You can prove consent was given (timestamp, IP, method, exact text)");
  lines.push("- [ ] **Freely given** — Consent is not bundled with T&Cs; separate consent for each purpose");
  lines.push("- [ ] **Specific** — Each consent type maps to a specific, named processing purpose");
  lines.push("- [ ] **Informed** — The consent text clearly identifies the controller and processing purposes");
  lines.push("- [ ] **Unambiguous** — Consent requires a clear affirmative action (no pre-ticked boxes)");
  lines.push("- [ ] **Withdrawable (Art. 7(3))** — Withdrawal is as easy as giving consent");
  lines.push("- [ ] **Recorded** — All consent events (grant, modify, withdraw) are immutably logged");
  lines.push("- [ ] **Versioned** — The policy version shown at consent time is recorded");
  lines.push("- [ ] **Age-verified** — For children, parental consent is obtained per Art. 8");
  lines.push("");

  // ── 7. Storage & Retention ──────────────────────────────────────────────
  lines.push("## 7. Storage & Retention");
  lines.push("");
  lines.push("| Aspect | Requirement |");
  lines.push("|--------|-------------|");
  lines.push("| **Storage** | Consent records must be stored in an append-only, tamper-evident log |");
  lines.push("| **Encryption** | Records must be encrypted at rest (AES-256) and in transit (TLS 1.2+) |");
  lines.push("| **Access** | Read access limited to DPO, legal, and authorised compliance staff |");
  lines.push("| **Retention** | Retain for the duration of the processing activity + 3 years |");
  lines.push("| **Deletion** | Consent records may only be deleted after the retention period expires |");
  lines.push("| **Backup** | Include in regular backup procedures; test restoration annually |");
  lines.push("");

  // ── 8. Implementation Guidance ──────────────────────────────────────────
  lines.push("## 8. Implementation Guidance");
  lines.push("");
  lines.push("### Database Schema (Example)");
  lines.push("");
  lines.push("```sql");
  lines.push("CREATE TABLE consent_records (");
  lines.push("  consent_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),");
  lines.push("  user_id         VARCHAR(255) NOT NULL,");
  lines.push("  timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),");
  lines.push("  consent_type    VARCHAR(50) NOT NULL,");
  lines.push("  consent_action  VARCHAR(20) NOT NULL CHECK (consent_action IN ('granted', 'withdrawn', 'modified', 'expired')),");
  lines.push("  ip_address      INET NOT NULL,");
  lines.push("  user_agent      TEXT NOT NULL,");
  lines.push("  method          VARCHAR(30) NOT NULL,");
  lines.push("  policy_version  VARCHAR(20) NOT NULL,");
  lines.push("  consent_text    TEXT NOT NULL,");
  lines.push("  language        VARCHAR(5) NOT NULL DEFAULT 'en',");
  lines.push("  expiry_date     TIMESTAMPTZ,");
  lines.push("  parent_consent_id UUID REFERENCES consent_records(consent_id),");
  lines.push("  source_url      TEXT,");
  lines.push("  geo_location    VARCHAR(10),");
  lines.push("  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()");
  lines.push(");");
  lines.push("");
  lines.push("CREATE INDEX idx_consent_user ON consent_records(user_id);");
  lines.push("CREATE INDEX idx_consent_type ON consent_records(consent_type);");
  lines.push("CREATE INDEX idx_consent_timestamp ON consent_records(timestamp);");
  lines.push("```");
  lines.push("");

  // ── 9. Audit & Review ──────────────────────────────────────────────────
  lines.push("## 9. Audit & Review");
  lines.push("");
  lines.push("| Activity | Frequency | Responsible |");
  lines.push("|----------|-----------|-------------|");
  lines.push(`| Review consent record completeness | Quarterly | ${dpoEmail} |`);
  lines.push(`| Audit consent collection mechanisms | Annually | ${dpoEmail} |`);
  lines.push("| Test consent withdrawal flow | Quarterly | Engineering |");
  lines.push("| Review consent text for accuracy | After each policy update | Legal |");
  lines.push("| Verify retention and deletion | Annually | Engineering |");
  lines.push("");

  // ── Contact ─────────────────────────────────────────────────────────────
  lines.push("## 10. Contact");
  lines.push("");
  lines.push("For questions about consent records or this template:");
  lines.push("");
  lines.push(`- **DPO:** ${dpoEmail}`);
  lines.push(`- **General Contact:** ${contactEmail}`);
  lines.push(`- **Website:** ${website}`);
  lines.push("");

  // ── Footer ─────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Consent Record Template was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
    "Adapt the consent types and fields to match your specific processing activities. Review with your DPO and legal counsel before implementation.*",
  );
  lines.push("");

  return lines.join("\n");
}
