import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates DATA_PROTECTION_POLICY.md — an internal data protection policy
 * covering classification, handling, access control, and disposal.
 * Based on detected data types from the scan.
 *
 * Returns null when no services are detected (no data processing).
 */
export function generateDataProtectionPolicy(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoName = ctx?.dpoName || "[Data Protection Officer Name]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const date = new Date().toISOString().split("T")[0];

  const hasAuth = scan.services.some((s) => s.category === "auth");
  const hasPayment = scan.services.some((s) => s.category === "payment");
  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasAnalytics = scan.services.some((s) => s.category === "analytics");
  const hasStorage = scan.services.some((s) => s.category === "storage");
  const hasDatabase = scan.services.some((s) => s.category === "database");
  const hasEmail = scan.services.some((s) => s.category === "email");
  const hasMonitoring = scan.services.some((s) => s.category === "monitoring");

  // Collect all unique data types from scan
  const allDataTypes = new Set<string>();
  for (const svc of scan.services) {
    for (const d of svc.dataCollected) {
      allDataTypes.add(d);
    }
  }

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Data Protection Policy");
  lines.push("");
  lines.push(`> **${company}** — Internal Data Protection Policy`);
  lines.push(`>`);
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(`>`);
  lines.push(`> **Policy Owner:** ${dpoName}`);
  lines.push(`>`);
  lines.push(`> Generated by [Codepliant](https://github.com/codepliant/codepliant)`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Purpose and Scope ────────────────────────────────────────────────
  lines.push("## 1. Purpose and Scope");
  lines.push("");
  lines.push(
    `This Data Protection Policy establishes the principles, standards, and responsibilities for protecting personal data and sensitive information processed by ${company}. It applies to all employees, contractors, and third parties who access or process data on behalf of the organization.`,
  );
  lines.push("");
  lines.push("### Scope");
  lines.push("");
  lines.push("This policy covers:");
  lines.push("");
  lines.push("- All personal data processed in connection with our products and services");
  lines.push("- Employee and contractor personal data");
  lines.push("- Data stored in electronic and physical formats");
  lines.push("- Data processed by third-party services and sub-processors");
  lines.push("");

  // ── 2. Data Classification ──────────────────────────────────────────────
  lines.push("## 2. Data Classification");
  lines.push("");
  lines.push(
    "All data processed by the organization must be classified according to the following levels:",
  );
  lines.push("");
  lines.push("| Classification | Description | Examples | Handling Requirements |");
  lines.push("|---------------|-------------|----------|----------------------|");
  lines.push("| **Restricted** | Highly sensitive data — unauthorized disclosure would cause severe harm | Payment card data, authentication credentials, encryption keys | Encrypted at rest and in transit, access logged, need-to-know basis only |");
  lines.push("| **Confidential** | Sensitive personal data or business-critical information | PII (names, emails, addresses), health data, financial records | Encrypted in transit, access controlled, retention limits enforced |");
  lines.push("| **Internal** | Non-public data intended for internal use | Analytics data, error logs, internal communications | Access restricted to authorized personnel, not shared externally |");
  lines.push("| **Public** | Data intended for public access | Marketing content, published documentation, public APIs | No special handling required |");
  lines.push("");

  // Detected data classification
  lines.push("### Detected Data Types and Classifications");
  lines.push("");
  lines.push("Based on automated code analysis, the following data types have been identified:");
  lines.push("");
  lines.push("| Data Type | Classification | Source |");
  lines.push("|-----------|---------------|--------|");

  if (hasPayment) {
    lines.push("| Payment card details | **Restricted** | Payment processing services |");
    lines.push("| Billing address | **Confidential** | Payment processing services |");
    lines.push("| Transaction history | **Confidential** | Payment processing services |");
  }
  if (hasAuth) {
    lines.push("| Authentication credentials | **Restricted** | Authentication services |");
    lines.push("| User identifiers (name, email) | **Confidential** | Authentication services |");
    lines.push("| Session tokens | **Restricted** | Authentication services |");
  }
  if (hasAI) {
    lines.push("| AI input data (user prompts) | **Confidential** | AI services |");
    lines.push("| AI-generated outputs | **Internal** | AI services |");
  }
  if (hasAnalytics) {
    lines.push("| Usage analytics | **Internal** | Analytics services |");
    lines.push("| IP addresses | **Confidential** | Analytics services |");
    lines.push("| Device information | **Internal** | Analytics services |");
  }
  if (hasStorage) {
    lines.push("| Uploaded files and media | **Confidential** | Storage services |");
  }
  if (hasDatabase) {
    lines.push("| User profile data | **Confidential** | Database services |");
    lines.push("| Application data | **Internal** | Database services |");
  }
  if (hasEmail) {
    lines.push("| Email addresses | **Confidential** | Email services |");
    lines.push("| Communication records | **Internal** | Email services |");
  }
  if (hasMonitoring) {
    lines.push("| Error reports | **Internal** | Monitoring services |");
    lines.push("| Performance metrics | **Internal** | Monitoring services |");
  }
  lines.push("");

  // ── 3. Data Handling Procedures ─────────────────────────────────────────
  lines.push("## 3. Data Handling Procedures");
  lines.push("");

  lines.push("### 3.1 Collection");
  lines.push("");
  lines.push("- Collect only the minimum data necessary for the stated purpose (data minimization)");
  lines.push("- Obtain appropriate consent or establish lawful basis before processing");
  lines.push("- Provide clear privacy notices at all data collection points");
  lines.push("- Document the purpose and lawful basis for each data collection activity");
  lines.push("");

  lines.push("### 3.2 Storage");
  lines.push("");
  lines.push("- **Restricted data** must be encrypted at rest using AES-256 or equivalent");
  lines.push("- **Confidential data** must be stored in access-controlled systems");
  lines.push("- All personal data must be stored in approved locations only");
  lines.push("- No personal data on local workstations, USB drives, or personal cloud storage");

  if (hasDatabase) {
    lines.push("- Database access must use parameterized queries to prevent injection attacks");
    lines.push("- Database backups must be encrypted and tested regularly");
  }
  if (hasStorage) {
    lines.push("- Uploaded files must be scanned for malware before storage");
    lines.push("- Storage buckets must not be publicly accessible by default");
  }
  lines.push("");

  lines.push("### 3.3 Transmission");
  lines.push("");
  lines.push("- All data transmitted over networks must use TLS 1.2 or higher");
  lines.push("- API keys and credentials must never be transmitted in URLs or query parameters");
  lines.push("- Email containing personal data must use encryption where possible");
  lines.push("- File transfers to third parties must use approved secure channels");
  lines.push("");

  lines.push("### 3.4 Processing");
  lines.push("");
  lines.push("- Process data only for the purposes documented in the Record of Processing Activities");
  lines.push("- Implement pseudonymization or anonymization where feasible");
  lines.push("- Log all access to Restricted and Confidential data");

  if (hasAI) {
    lines.push("- AI models must not be trained on customer personal data without explicit consent");
    lines.push("- AI processing outputs must be reviewed for unintended personal data exposure");
  }
  if (hasAnalytics) {
    lines.push("- Analytics data must be anonymized or pseudonymized where possible");
    lines.push("- User consent must be obtained before analytics tracking is enabled");
  }
  lines.push("");

  // ── 4. Access Control ───────────────────────────────────────────────────
  lines.push("## 4. Access Control");
  lines.push("");
  lines.push("### 4.1 Principles");
  lines.push("");
  lines.push("- **Least Privilege:** Grant the minimum access necessary for the role");
  lines.push("- **Need-to-Know:** Access to personal data only when required for job function");
  lines.push("- **Separation of Duties:** Critical operations require approval from multiple parties");
  lines.push("");

  lines.push("### 4.2 Access Levels");
  lines.push("");
  lines.push("| Role | Restricted Data | Confidential Data | Internal Data | Public Data |");
  lines.push("|------|----------------|-------------------|---------------|-------------|");
  lines.push("| Administrator | Read/Write (logged) | Read/Write | Read/Write | Read/Write |");
  lines.push("| Developer | No access | Read (in production) | Read/Write | Read/Write |");
  lines.push("| Support Staff | No access | Read (with justification) | Read | Read |");
  lines.push("| Third-Party Contractor | No access | As per DPA only | As per contract | Read |");
  lines.push("");

  lines.push("### 4.3 Access Management");
  lines.push("");
  lines.push("- All access must be authenticated and authorized");

  if (hasAuth) {
    lines.push("- Multi-factor authentication (MFA) is required for admin access and production systems");
    lines.push("- Authentication sessions must have appropriate timeout periods");
  }

  lines.push("- Access permissions must be reviewed quarterly");
  lines.push("- Access must be revoked within 24 hours of role change or termination");
  lines.push("- Shared accounts are prohibited for accessing personal data");
  lines.push("");

  // ── 5. Data Disposal ────────────────────────────────────────────────────
  lines.push("## 5. Data Disposal");
  lines.push("");
  lines.push("### 5.1 Retention Periods");
  lines.push("");
  lines.push("Data must be disposed of when it is no longer needed for the stated purpose or when the retention period expires:");
  lines.push("");
  lines.push("| Data Type | Maximum Retention | Disposal Method |");
  lines.push("|-----------|------------------|-----------------|");

  if (hasAuth) {
    lines.push("| Account data | Duration of account + 30 days | Secure deletion from all systems |");
  }
  if (hasPayment) {
    lines.push("| Payment/transaction records | 7 years (legal requirement) | Secure archival then deletion |");
  }
  if (hasAnalytics) {
    lines.push("| Analytics data | 26 months | Automated purge |");
  }
  if (hasMonitoring) {
    lines.push("| Error logs and monitoring data | 90 days | Automated purge |");
  }
  if (hasAI) {
    lines.push("| AI interaction data | 90 days | Automated purge |");
  }
  if (hasEmail) {
    lines.push("| Email communications | 3 years | Secure deletion |");
  }
  if (hasStorage) {
    lines.push("| Uploaded files | Duration of account | Secure deletion on account closure |");
  }
  if (hasDatabase) {
    lines.push("| User profile data | Duration of account + 30 days | Secure deletion from all systems |");
  }

  lines.push("| Backups containing personal data | 90 days after source deletion | Automated purge from backup rotation |");
  lines.push("");

  lines.push("### 5.2 Disposal Methods");
  lines.push("");
  lines.push("- **Electronic data:** Cryptographic erasure or overwriting with random data");
  lines.push("- **Database records:** Secure deletion with verification from all replicas and caches");
  lines.push("- **Backups:** Allowed to expire naturally from backup rotation (max 90 days)");
  lines.push("- **Physical media:** Shredding or degaussing");
  lines.push("- **Third-party data:** Written confirmation of deletion from sub-processors");
  lines.push("");

  lines.push("### 5.3 Disposal Verification");
  lines.push("");
  lines.push("- Maintain a log of all data disposal activities");
  lines.push("- Verify deletion from all systems, including backups and caches");
  lines.push("- Obtain written confirmation from third parties when data is deleted on their systems");
  lines.push("");

  // ── 6. Incident Response ────────────────────────────────────────────────
  lines.push("## 6. Data Protection Incidents");
  lines.push("");
  lines.push("Any suspected or actual data protection incident must be reported immediately:");
  lines.push("");
  lines.push("1. **Report** the incident to the Data Protection Officer within 4 hours of discovery");
  lines.push("2. **Assess** the severity, scope, and potential impact on data subjects");
  lines.push("3. **Contain** the incident to prevent further data loss");
  lines.push("4. **Notify** supervisory authorities within 72 hours if required (GDPR Art. 33)");
  lines.push("5. **Notify** affected data subjects without undue delay if high risk (GDPR Art. 34)");
  lines.push("6. **Document** the incident, response actions, and lessons learned");
  lines.push("");
  lines.push("Refer to the Incident Response Plan (`INCIDENT_RESPONSE_PLAN.md`) for detailed procedures.");
  lines.push("");

  // ── 7. Training and Awareness ───────────────────────────────────────────
  lines.push("## 7. Training and Awareness");
  lines.push("");
  lines.push("- All employees must complete data protection training within 30 days of joining");
  lines.push("- Annual refresher training is mandatory for all staff");
  lines.push("- Specialized training for roles with access to Restricted or Confidential data");
  lines.push("- Training records must be maintained for audit purposes");
  lines.push("");

  // ── 8. Third-Party Requirements ─────────────────────────────────────────
  lines.push("## 8. Third-Party Data Processors");
  lines.push("");
  lines.push("All third-party processors must:");
  lines.push("");
  lines.push("- Sign a Data Processing Agreement (DPA) before processing begins");
  lines.push("- Demonstrate adequate technical and organizational security measures");
  lines.push("- Process data only on documented instructions from the controller");
  lines.push("- Notify us of any sub-processor changes (see Sub-Processor Change Notification process)");
  lines.push("- Delete or return all personal data at the end of the engagement");
  lines.push("");

  if (scan.services.length >= 3) {
    const thirdParty = scan.services.filter(
      (s) => s.category !== "database" && !["prisma", "drizzle", "mongoose", "ioredis", "redis"].includes(s.name),
    );
    if (thirdParty.length > 0) {
      lines.push("### Currently Engaged Processors");
      lines.push("");
      lines.push("| Service | Category | DPA Required |");
      lines.push("|---------|----------|-------------|");
      const seen = new Set<string>();
      for (const svc of thirdParty) {
        if (seen.has(svc.name)) continue;
        seen.add(svc.name);
        lines.push(`| ${svc.name} | ${svc.category} | - [ ] Signed |`);
      }
      lines.push("");
    }
  }

  // ── 9. Compliance and Monitoring ────────────────────────────────────────
  lines.push("## 9. Compliance and Monitoring");
  lines.push("");
  lines.push("- This policy must be reviewed at least annually or after significant changes");
  lines.push("- Compliance audits will be conducted at least annually");
  lines.push("- Non-compliance may result in disciplinary action, up to and including termination");
  lines.push("- All data protection activities must be documented for regulatory accountability");
  lines.push("");

  // ── 10. Roles and Responsibilities ──────────────────────────────────────
  lines.push("## 10. Roles and Responsibilities");
  lines.push("");
  lines.push("| Role | Responsibilities |");
  lines.push("|------|-----------------|");
  lines.push(`| **Data Protection Officer** (${dpoName}) | Oversee compliance, handle DSARs, liaise with authorities, conduct DPIAs |`);
  lines.push("| **Management** | Ensure policy is implemented, allocate resources, support DPO |");
  lines.push("| **IT/Engineering** | Implement technical controls, maintain security measures, manage access |");
  lines.push("| **All Employees** | Follow this policy, report incidents, complete training |");
  lines.push("");

  // ── Contact ─────────────────────────────────────────────────────────────
  lines.push("## 11. Contact");
  lines.push("");
  lines.push(`For questions about this policy or to report a data protection concern:`);
  lines.push("");
  lines.push(`- **Data Protection Officer:** ${dpoEmail}`);
  lines.push(`- **General Contact:** ${contactEmail}`);
  lines.push("");

  // ── Footer ──────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Data Protection Policy was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
      "It should be customized to reflect your organization's specific requirements and reviewed by legal counsel and your Data Protection Officer.*",
  );
  lines.push("");

  return lines.join("\n");
}
