import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates DATA_SUBJECT_CATEGORIES.md — GDPR Art. 30 requirement
 * documenting categories of data subjects whose data is processed.
 */
export function generateDataSubjectCategories(
  scan: ScanResult,
  ctx?: GeneratorContext,
  includeEmployees?: boolean,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const date = new Date().toISOString().split("T")[0];

  const sections: string[] = [];

  sections.push("# Data Subject Categories");
  sections.push("");
  sections.push(`**Last Updated:** ${date}`);
  sections.push(`**Organization:** ${company}`);
  sections.push(`**Project:** ${scan.projectName}`);
  sections.push("");
  sections.push("---");
  sections.push("");
  sections.push("## Overview");
  sections.push("");
  sections.push(
    "This document identifies the categories of individuals (data subjects) " +
    "whose personal data is processed by this system, as required by GDPR Article 30.",
  );
  sections.push("");

  sections.push("## Data Subject Categories");
  sections.push("");
  sections.push("| Category | Data Types | Legal Basis | Retention |");
  sections.push("|----------|-----------|-------------|-----------|");

  // Users/Customers — always when auth or payment detected
  const hasAuth = scan.services.some((s) => s.category === "auth");
  const hasPayment = scan.services.some((s) => s.category === "payment");
  const hasAnalytics = scan.services.some((s) => s.category === "analytics");

  if (hasAuth || hasPayment) {
    sections.push("| **End Users / Customers** | Name, email, account credentials, usage data | Contract performance (Art. 6(1)(b)) | Duration of account + 30 days |");
  }
  if (hasPayment) {
    sections.push("| **Paying Customers** | Payment method, billing address, transaction history | Contract performance (Art. 6(1)(b)) | As required by tax law |");
  }
  if (hasAnalytics) {
    sections.push("| **Website Visitors** | IP address, browser info, cookies, page views | Legitimate interest / Consent (Art. 6(1)(f)/(a)) | 26 months |");
  }
  if (includeEmployees) {
    sections.push("| **Employees** | Name, email, role, access logs | Contract performance (Art. 6(1)(b)) | Duration of employment + statutory |");
  }

  sections.push("| **Support Contacts** | Name, email, support ticket content | Legitimate interest (Art. 6(1)(f)) | 2 years after last contact |");

  sections.push("");

  sections.push("## Review Notes");
  sections.push("");
  sections.push("- Review frequency: Annually");
  sections.push("- Last reviewed: " + date);
  sections.push("- Next review: " + new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split("T")[0]);
  sections.push("");

  sections.push("## Related Documents");
  sections.push("");
  sections.push("- [Privacy Policy](./PRIVACY_POLICY.md)");
  sections.push("- [Record of Processing Activities](./RECORD_OF_PROCESSING_ACTIVITIES.md)");
  sections.push("- [Lawful Basis Assessment](./LAWFUL_BASIS_ASSESSMENT.md)");
  sections.push("");

  sections.push("---");
  sections.push("");
  sections.push("*Generated by Codepliant. Review with your DPO before finalizing.*");
  sections.push("");

  return sections.join("\n");
}
