import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { generateEnvExample, writeEnvExample } from "./env-example.js";
import type { ScanResult, DetectedService } from "../scanner/index.js";

// --- Test helpers ---

function makeService(
  name: string,
  category: DetectedService["category"],
  dataCollected: string[] = ["test data"],
  isDataProcessor?: boolean
): DetectedService {
  return {
    name,
    category,
    evidence: [{ type: "dependency", file: "package.json", detail: `${name} detected` }],
    dataCollected,
    ...(isDataProcessor !== undefined ? { isDataProcessor } : {}),
  };
}

function makeScan(services: DetectedService[] = []): ScanResult {
  return {
    projectName: "test-project",
    projectPath: "/tmp/test",
    scannedAt: "2026-01-01",
    services,
    dataCategories: [],
    complianceNeeds: [],
  };
}

describe("generateEnvExample", () => {
  it("returns empty string for empty scan", () => {
    const result = generateEnvExample(makeScan());
    assert.strictEqual(result, "");
  });

  it("returns empty string when no services have env patterns", () => {
    const scan = makeScan([
      makeService("@vercel/analytics", "analytics"),
      makeService("passport", "auth"),
    ]);
    const result = generateEnvExample(scan);
    assert.strictEqual(result, "");
  });

  it("generates env vars for OpenAI", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY=sk-your-key-here"));
    assert.ok(result.includes("# === AI Services ==="));
  });

  it("generates env vars for Stripe", () => {
    const scan = makeScan([makeService("stripe", "payment")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("STRIPE_SECRET_KEY=rk_test_REPLACE_ME"));
    assert.ok(result.includes("STRIPE_PUBLISHABLE_KEY=pk_test_your-key"));
    assert.ok(result.includes("STRIPE_WEBHOOK_SECRET=whsec_your-secret"));
    assert.ok(result.includes("# === Payment ==="));
  });

  it("generates env vars for Sentry", () => {
    const scan = makeScan([makeService("@sentry/node", "monitoring")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("SENTRY_DSN=https://"));
    assert.ok(result.includes("# === Monitoring ==="));
  });

  it("generates env vars for NextAuth", () => {
    const scan = makeScan([makeService("next-auth", "auth")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("NEXTAUTH_SECRET=your-secret-here"));
    assert.ok(result.includes("NEXTAUTH_URL=http://localhost:3000"));
    assert.ok(result.includes("# === Authentication ==="));
  });

  it("groups vars by category with section headers", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("stripe", "payment"),
      makeService("next-auth", "auth"),
    ]);
    const result = generateEnvExample(scan);

    const aiIdx = result.indexOf("# === AI Services ===");
    const paymentIdx = result.indexOf("# === Payment ===");
    const authIdx = result.indexOf("# === Authentication ===");

    assert.ok(aiIdx >= 0, "AI section header should exist");
    assert.ok(paymentIdx >= 0, "Payment section header should exist");
    assert.ok(authIdx >= 0, "Auth section header should exist");

    // AI comes before Payment, Payment before Auth (per CATEGORY_ORDER)
    assert.ok(aiIdx < paymentIdx, "AI should come before Payment");
    assert.ok(paymentIdx < authIdx, "Payment should come before Auth");
  });

  it("includes file header with instructions", () => {
    const scan = makeScan([makeService("openai", "ai")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("Generated by Codepliant"));
    assert.ok(result.includes("Copy this file to .env.local"));
    assert.ok(result.includes("NEVER commit .env.local"));
  });

  it("deduplicates env vars across services", () => {
    // Both sentry/node and sentry/nextjs use SENTRY_DSN
    const scan = makeScan([
      makeService("@sentry/node", "monitoring"),
      makeService("@sentry/nextjs", "monitoring"),
    ]);
    const result = generateEnvExample(scan);

    const matches = result.match(/^SENTRY_DSN=/gm);
    assert.strictEqual(matches?.length, 1, "SENTRY_DSN should appear exactly once");
  });

  it("excludes non-data-processor services", () => {
    const scan = makeScan([
      makeService("zod", "other", ["validated user input"], false),
      makeService("openai", "ai"),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY"));
    // zod has no env patterns anyway, but ensure it's filtered
    assert.ok(!result.includes("zod"));
  });

  it("generates database env vars", () => {
    const scan = makeScan([makeService("prisma", "database")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("PRISMA_DATABASE_URL="));
    assert.ok(result.includes("# === Database ==="));
  });

  it("generates email service env vars", () => {
    const scan = makeScan([makeService("@sendgrid/mail", "email")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("SENDGRID_API_KEY="));
    assert.ok(result.includes("# === Email ==="));
  });

  it("generates storage env vars", () => {
    const scan = makeScan([makeService("@aws-sdk/client-s3", "storage")]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("AWS_ACCESS_KEY_ID="));
    assert.ok(result.includes("AWS_SECRET_ACCESS_KEY="));
    assert.ok(result.includes("# === Storage ==="));
  });

  it("handles multiple services in same category", () => {
    const scan = makeScan([
      makeService("openai", "ai"),
      makeService("@anthropic-ai/sdk", "ai"),
    ]);
    const result = generateEnvExample(scan);
    assert.ok(result.includes("OPENAI_API_KEY="));
    assert.ok(result.includes("ANTHROPIC_API_KEY="));

    // Only one AI header
    const headers = result.match(/# === AI Services ===/g);
    assert.strictEqual(headers?.length, 1);
  });
});

describe("writeEnvExample", () => {
  it("writes .env.example file to disk", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const scan = makeScan([makeService("openai", "ai")]);
      const result = writeEnvExample(scan, tmpDir);

      assert.ok(result !== null);
      assert.ok(result!.endsWith(".env.example"));
      assert.ok(fs.existsSync(result!));

      const content = fs.readFileSync(result!, "utf-8");
      assert.ok(content.includes("OPENAI_API_KEY="));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("returns null when no services detected", () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codepliant-test-"));
    try {
      const result = writeEnvExample(makeScan(), tmpDir);
      assert.strictEqual(result, null);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it("creates output directory if it does not exist", () => {
    const tmpDir = path.join(os.tmpdir(), `codepliant-test-${Date.now()}`);
    try {
      const scan = makeScan([makeService("stripe", "payment")]);
      const result = writeEnvExample(scan, tmpDir);

      assert.ok(result !== null);
      assert.ok(fs.existsSync(tmpDir));
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});
