import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

interface CiCdScanResult {
  platforms?: { name: string }[];
  provider?: string;
  hasTests?: boolean;
  hasLinting?: boolean;
  hasAutomatedTests?: boolean;
  hasSecurityScanning?: boolean;
  hasDependencyScanning?: boolean;
  hasDependencyUpdates?: boolean;
  hasDeploymentPipeline?: boolean;
  hasVersionControl?: boolean;
  vcsProvider?: string | null;
}

/**
 * Generates INFORMATION_SECURITY_POLICY.md — umbrella ISMS policy
 * aligned with ISO 27001 and NIST Cybersecurity Framework.
 */
export function generateInformationSecurityPolicy(
  scan: ScanResult,
  ctx?: GeneratorContext,
  cicdScan?: CiCdScanResult | null,
): string | null {
  if (scan.services.length < 3) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const date = new Date().toISOString().split("T")[0];

  const sections: string[] = [];

  sections.push("# Information Security Policy");
  sections.push("");
  sections.push(`**Effective Date:** ${date}`);
  sections.push(`**Last Updated:** ${date}`);
  sections.push(`**Organization:** ${company}`);
  sections.push(`**Project:** ${scan.projectName}`);
  sections.push("");
  sections.push("---");
  sections.push("");

  sections.push("## 1. Purpose");
  sections.push("");
  sections.push(
    `This Information Security Policy establishes the framework for protecting ` +
    `${company}'s information assets. It aligns with ISO 27001 and NIST CSF standards.`,
  );
  sections.push("");

  sections.push("## 2. Scope");
  sections.push("");
  sections.push("This policy applies to:");
  sections.push("");
  sections.push("- All information systems and data assets");
  sections.push("- All employees, contractors, and third-party users");
  sections.push(`- All ${scan.services.length} integrated services detected in this project`);
  sections.push("");

  sections.push("## 3. Information Security Objectives");
  sections.push("");
  sections.push("- **Confidentiality** — Protect information from unauthorized access");
  sections.push("- **Integrity** — Ensure accuracy and completeness of information");
  sections.push("- **Availability** — Ensure authorized users have access when needed");
  sections.push("");

  sections.push("## 4. Roles and Responsibilities");
  sections.push("");
  sections.push("| Role | Responsibility |");
  sections.push("|------|---------------|");
  sections.push("| CISO / Security Lead | Overall security strategy and policy enforcement |");
  sections.push("| Development Team | Secure coding practices, vulnerability remediation |");
  sections.push("| Operations Team | Infrastructure security, access management |");
  sections.push("| All Staff | Compliance with this policy, incident reporting |");
  sections.push("");

  sections.push("## 5. Access Control");
  sections.push("");
  sections.push("- Principle of least privilege for all system access");
  sections.push("- Multi-factor authentication required for production systems");
  sections.push("- Access reviews conducted quarterly");
  sections.push("- Immediate access revocation upon role change or termination");
  sections.push("");

  if (cicdScan) {
    sections.push("## 6. Development Security");
    sections.push("");
    const providerName = cicdScan.provider || (cicdScan.platforms && cicdScan.platforms.length > 0 ? cicdScan.platforms.map(p => p.name).join(", ") : "Unknown");
    sections.push(`CI/CD provider: **${providerName}**`);
    sections.push("");
    const hasTests = cicdScan.hasTests ?? cicdScan.hasAutomatedTests ?? false;
    sections.push(`- Automated testing: ${hasTests ? "Enabled" : "Not detected — recommended"}`);
    sections.push(`- Linting: ${cicdScan.hasLinting ? "Enabled" : "Not detected — recommended"}`);
    sections.push(`- Security scanning: ${cicdScan.hasSecurityScanning ? "Enabled" : "Not detected — recommended"}`);
    const hasDeps = cicdScan.hasDependencyScanning ?? cicdScan.hasDependencyUpdates ?? false;
    sections.push(`- Dependency scanning: ${hasDeps ? "Enabled" : "Not detected — recommended"}`);
    sections.push("");
  }

  sections.push("## 7. Incident Management");
  sections.push("");
  sections.push("- All security incidents must be reported within 1 hour of discovery");
  sections.push(`- Security incidents: ${contactEmail}`);
  sections.push("- See [Incident Response Plan](./INCIDENT_RESPONSE_PLAN.md) for detailed procedures");
  sections.push("");

  sections.push("## 8. Policy Review");
  sections.push("");
  sections.push("This policy is reviewed annually or upon significant changes to the information security environment.");
  sections.push("");

  sections.push("---");
  sections.push("");
  sections.push("*Generated by Codepliant. Review with your security team before adopting.*");
  sections.push("");

  return sections.join("\n");
}
