import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates MEDIA_CONSENT_FORM.md — a template for user media consent
 * covering photo/video usage rights. Generated when storage services
 * (file uploads) are detected.
 *
 * Returns null when no storage services are detected.
 */
export function generateMediaConsentForm(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  const hasStorage = scan.services.some((s) => s.category === "storage");

  if (!hasStorage) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const website = ctx?.website || "[https://yoursite.com]";
  const date = new Date().toISOString().split("T")[0];

  // Identify specific storage services
  const storageServices = scan.services.filter((s) => s.category === "storage");
  const storageNames = storageServices.map((s) => s.name).join(", ");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Media Consent Form");
  lines.push("");
  lines.push(`> **${company}** — Media Usage Consent`);
  lines.push(`>`);
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(`>`);
  lines.push(`> Generated by [Codepliant](https://github.com/codepliant/codepliant)`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Introduction ─────────────────────────────────────────────────────
  lines.push("## 1. Introduction");
  lines.push("");
  lines.push(
    `${company} ("we," "us," or "our") respects your rights regarding media content (photographs, videos, audio recordings, and other visual/audio materials). This consent form explains how we collect, use, store, and share media content and provides you with the ability to grant or withdraw your consent.`,
  );
  lines.push("");

  // ── 2. Media We Collect ─────────────────────────────────────────────────
  lines.push("## 2. Types of Media Covered");
  lines.push("");
  lines.push("This consent covers the following types of media content:");
  lines.push("");
  lines.push("- **Photographs** — profile pictures, uploaded images, photo content");
  lines.push("- **Videos** — uploaded video content, recorded sessions");
  lines.push("- **Audio** — voice recordings, audio uploads");
  lines.push("- **Documents** — uploaded files containing visual or media content");
  lines.push("");
  lines.push(`**Storage Services Used:** ${storageNames}`);
  lines.push("");

  // ── 3. Purpose of Collection ────────────────────────────────────────────
  lines.push("## 3. Purpose of Collection and Use");
  lines.push("");
  lines.push("We may use your media content for the following purposes (check all that apply):");
  lines.push("");
  lines.push("- [ ] **Service Delivery** — Providing the core features of our service (e.g., profile pictures, content uploads)");
  lines.push("- [ ] **Marketing and Promotion** — Using media in marketing materials, social media, or advertising");
  lines.push("- [ ] **Testimonials** — Featuring your content or likeness in customer testimonials");
  lines.push("- [ ] **Internal Training** — Using media for internal training or quality improvement");
  lines.push("- [ ] **Research and Development** — Analyzing media to improve products and services");
  lines.push("- [ ] **Public Relations** — Using media in press releases, articles, or public communications");
  lines.push("- [ ] **Other:** [Specify additional purposes]");
  lines.push("");

  // ── 4. Consent Declaration ──────────────────────────────────────────────
  lines.push("## 4. Consent Declaration");
  lines.push("");
  lines.push("By signing below or clicking the consent button, I acknowledge and agree that:");
  lines.push("");
  lines.push(`1. I grant ${company} a non-exclusive, royalty-free license to use, reproduce, modify, publish, and distribute the media content I upload or provide, for the purposes indicated above.`);
  lines.push("2. This consent is given voluntarily and I understand I may withdraw it at any time.");
  lines.push("3. I am the rightful owner of the media content, or I have obtained all necessary permissions from any individuals depicted or recorded.");
  lines.push(`4. I understand that media shared prior to withdrawal of consent may continue to exist in previously distributed materials, though ${company} will make reasonable efforts to remove it from active use.`);
  lines.push("5. I am at least 18 years of age, or a parent/guardian has provided consent on my behalf.");
  lines.push("");

  // ── 5. Specific Media Permissions ───────────────────────────────────────
  lines.push("## 5. Specific Permissions");
  lines.push("");
  lines.push("Please indicate your consent for each type of use:");
  lines.push("");
  lines.push("| Use Type | Consent | Notes |");
  lines.push("|----------|---------|-------|");
  lines.push("| Use within the application/service | - [ ] Yes / - [ ] No | Required for core service functionality |");
  lines.push("| Display on our website | - [ ] Yes / - [ ] No | |");
  lines.push("| Use in social media posts | - [ ] Yes / - [ ] No | |");
  lines.push("| Use in marketing/advertising | - [ ] Yes / - [ ] No | |");
  lines.push("| Use in print materials | - [ ] Yes / - [ ] No | |");
  lines.push("| Sharing with third-party partners | - [ ] Yes / - [ ] No | |");
  lines.push("| Use in press/media coverage | - [ ] Yes / - [ ] No | |");
  lines.push("");

  // ── 6. Duration ─────────────────────────────────────────────────────────
  lines.push("## 6. Duration of Consent");
  lines.push("");
  lines.push("This consent is valid:");
  lines.push("");
  lines.push("- [ ] **Indefinitely** — until I withdraw my consent");
  lines.push("- [ ] **For a specific period:** from [Start Date] to [End Date]");
  lines.push("- [ ] **For a specific project/campaign:** [Project Name]");
  lines.push("");

  // ── 7. Your Rights ──────────────────────────────────────────────────────
  lines.push("## 7. Your Rights");
  lines.push("");
  lines.push("You have the following rights regarding your media content:");
  lines.push("");
  lines.push("### Right to Withdraw Consent");
  lines.push("");
  lines.push(
    `You may withdraw your consent at any time by contacting us at ${dpoEmail}. Withdrawal of consent does not affect the lawfulness of processing performed before the withdrawal.`,
  );
  lines.push("");
  lines.push("### Right to Access");
  lines.push("");
  lines.push("You may request a copy of all media content we hold that contains your likeness or that you have uploaded.");
  lines.push("");
  lines.push("### Right to Deletion");
  lines.push("");
  lines.push(
    "You may request that we delete your media content from our systems. We will comply within 30 days, except where retention is required by law.",
  );
  lines.push("");
  lines.push("### Right to Restrict Processing");
  lines.push("");
  lines.push("You may request that we limit how we use your media content without deleting it entirely.");
  lines.push("");

  // ── 8. Minors ───────────────────────────────────────────────────────────
  lines.push("## 8. Minors");
  lines.push("");
  lines.push("For individuals under the age of 18:");
  lines.push("");
  lines.push("- A parent or legal guardian must sign this consent form");
  lines.push("- The parent/guardian may withdraw consent at any time");
  lines.push("- We will not knowingly collect media from minors without parental consent");
  lines.push("");

  // ── 9. Data Protection ──────────────────────────────────────────────────
  lines.push("## 9. Data Protection");
  lines.push("");
  lines.push("Your media content is protected by:");
  lines.push("");
  lines.push("- Encryption in transit (TLS) and at rest");
  lines.push("- Access controls limiting who can view and manage media");
  lines.push("- Regular security audits of storage systems");
  lines.push(`- Compliance with our Privacy Policy (see ${website}/privacy)`);
  lines.push("");
  lines.push(`For full details on how we protect your data, see our Privacy Policy (\`PRIVACY_POLICY.md\`) and Data Protection Policy (\`DATA_PROTECTION_POLICY.md\`).`);
  lines.push("");

  // ── 10. Signature ───────────────────────────────────────────────────────
  lines.push("## 10. Signature");
  lines.push("");
  lines.push("| Field | Details |");
  lines.push("|-------|---------|");
  lines.push("| **Full Name** | |");
  lines.push("| **Email Address** | |");
  lines.push("| **Date** | |");
  lines.push("| **Signature** | |");
  lines.push("");
  lines.push("**For Minors (if applicable):**");
  lines.push("");
  lines.push("| Field | Details |");
  lines.push("|-------|---------|");
  lines.push("| **Parent/Guardian Name** | |");
  lines.push("| **Relationship to Minor** | |");
  lines.push("| **Date** | |");
  lines.push("| **Signature** | |");
  lines.push("");

  // ── Contact ─────────────────────────────────────────────────────────────
  lines.push("## 11. Contact");
  lines.push("");
  lines.push("For questions about this consent form or to exercise your rights:");
  lines.push("");
  lines.push(`- **Email:** ${dpoEmail}`);
  lines.push(`- **General Contact:** ${contactEmail}`);
  lines.push(`- **Website:** ${website}`);
  lines.push("");

  // ── Footer ──────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Media Consent Form was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
      "Customize the purposes and permissions to match your actual media usage practices. Review with legal counsel before use.*",
  );
  lines.push("");

  return lines.join("\n");
}
