import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates PRIVACY_PROGRAM_CHARTER.md — establishes the organization's
 * privacy program with mission, scope, governance structure, key roles,
 * annual objectives, and metrics.
 *
 * Always generated when services are detected (every organization processing
 * personal data needs a formal privacy program).
 */
export function generatePrivacyProgramCharter(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoName = ctx?.dpoName || "[Data Protection Officer Name]";
  const dpoEmail = ctx?.dpoEmail || "[dpo@example.com]";
  const website = ctx?.website || "[https://yoursite.com]";
  const date = new Date().toISOString().split("T")[0];

  const jurisdiction = ctx?.jurisdiction || "";
  const jurisdictions = ctx?.jurisdictions || [];
  const allJurisdictions = new Set<string>();
  if (jurisdiction) allJurisdictions.add(jurisdiction);
  for (const j of jurisdictions) allJurisdictions.add(j);

  const hasEU = allJurisdictions.has("EU") || allJurisdictions.has("UK");
  const hasUS = allJurisdictions.has("US") || allJurisdictions.has("CCPA");
  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasAnalytics = scan.services.some((s) => s.category === "analytics");
  const hasPayment = scan.services.some((s) => s.category === "payment");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Privacy Program Charter");
  lines.push("");
  lines.push(`> **${company}** — Formal Privacy Program Establishment`);
  lines.push(">");
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(">");
  lines.push("> Generated by [Codepliant](https://github.com/codepliant/codepliant)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Mission Statement ──────────────────────────────────────────────
  lines.push("## 1. Mission Statement");
  lines.push("");
  lines.push(
    `The Privacy Program of ${company} exists to protect the personal data of all individuals whose information we collect, process, or store. Our mission is to embed privacy into every aspect of our operations, maintain compliance with applicable data protection regulations, and foster a culture of transparency and accountability.`,
  );
  lines.push("");
  lines.push("### 1.1 Core Principles");
  lines.push("");
  lines.push("1. **Privacy by Design** — Build privacy protections into products and processes from the outset");
  lines.push("2. **Data Minimisation** — Collect only what is necessary for the stated purpose");
  lines.push("3. **Transparency** — Clearly communicate data practices to all stakeholders");
  lines.push("4. **Accountability** — Maintain demonstrable compliance with all applicable regulations");
  lines.push("5. **Security** — Protect personal data with appropriate technical and organisational measures");
  lines.push("");

  // ── 2. Scope ──────────────────────────────────────────────────────────
  lines.push("## 2. Scope");
  lines.push("");
  lines.push("This charter applies to:");
  lines.push("");
  lines.push(`- All ${company} employees, contractors, and temporary staff`);
  lines.push("- All business units and departments");
  lines.push("- All systems and applications that process personal data");
  lines.push("- All third-party vendors and sub-processors");
  lines.push("- All data subjects whose information is processed");
  lines.push("");

  lines.push("### 2.1 Data Processing Landscape");
  lines.push("");
  lines.push(`Based on automated code analysis, ${company} currently processes data through **${scan.services.length} detected service(s)**:`);
  lines.push("");

  const categories = new Map<string, string[]>();
  for (const svc of scan.services) {
    const cat = svc.category || "other";
    if (!categories.has(cat)) categories.set(cat, []);
    categories.get(cat)!.push(svc.name);
  }
  for (const [cat, svcs] of categories) {
    lines.push(`- **${cat.charAt(0).toUpperCase() + cat.slice(1)}:** ${svcs.join(", ")}`);
  }
  lines.push("");

  if (scan.dataCategories && scan.dataCategories.length > 0) {
    lines.push("### 2.2 Data Categories in Scope");
    lines.push("");
    for (const dc of scan.dataCategories) {
      lines.push(`- ${dc}`);
    }
    lines.push("");
  }

  // ── 3. Regulatory Framework ───────────────────────────────────────────
  lines.push("## 3. Regulatory Framework");
  lines.push("");
  lines.push("The Privacy Program is designed to comply with the following regulations:");
  lines.push("");
  lines.push("| Regulation | Jurisdiction | Key Requirements |");
  lines.push("|-----------|-------------|------------------|");
  if (hasEU) {
    lines.push("| GDPR | EU/EEA | Lawful basis, data subject rights, DPO, DPIA, breach notification |");
    lines.push("| ePrivacy Directive | EU/EEA | Cookie consent, electronic communications |");
  }
  if (allJurisdictions.has("UK")) {
    lines.push("| UK GDPR + DPA 2018 | United Kingdom | UK-specific data protection requirements |");
  }
  if (hasUS) {
    lines.push("| CCPA/CPRA | California, US | Consumer rights, opt-out, data sale restrictions |");
  }
  if (hasAI) {
    lines.push("| EU AI Act | EU/EEA | AI risk classification, transparency, human oversight |");
  }
  lines.push("| Industry standards | Global | SOC 2, ISO 27001, NIST CSF (as applicable) |");
  lines.push("");

  // ── 4. Governance Structure ───────────────────────────────────────────
  lines.push("## 4. Governance Structure");
  lines.push("");
  lines.push("### 4.1 Privacy Governance Hierarchy");
  lines.push("");
  lines.push("```");
  lines.push("┌─────────────────────────────────┐");
  lines.push("│        Board of Directors        │  Ultimate accountability");
  lines.push("├─────────────────────────────────┤");
  lines.push("│     Executive Leadership         │  Strategic oversight");
  lines.push("│     (CEO / COO / CTO)            │");
  lines.push("├─────────────────────────────────┤");
  lines.push("│   Privacy Steering Committee     │  Cross-functional governance");
  lines.push("├─────────────────────────────────┤");
  lines.push("│   Data Protection Officer (DPO)  │  Day-to-day program management");
  lines.push("├─────────────────────────────────┤");
  lines.push("│   Privacy Champions (per team)   │  Departmental privacy advocates");
  lines.push("└─────────────────────────────────┘");
  lines.push("```");
  lines.push("");

  lines.push("### 4.2 Privacy Steering Committee");
  lines.push("");
  lines.push("| Aspect | Detail |");
  lines.push("|--------|--------|");
  lines.push("| **Composition** | DPO (Chair), CTO, Legal Counsel, Head of Engineering, Head of Product, CISO |");
  lines.push("| **Meeting cadence** | Quarterly (monthly if active incidents or regulatory changes) |");
  lines.push("| **Quorum** | DPO + 3 additional members |");
  lines.push("| **Reporting** | Minutes distributed to all members; quarterly summary to Board |");
  lines.push("| **Decision authority** | Approve DPIAs, vendor assessments, policy changes, breach responses |");
  lines.push("");

  // ── 5. Key Roles & Responsibilities ──────────────────────────────────
  lines.push("## 5. Key Roles & Responsibilities");
  lines.push("");
  lines.push("### 5.1 Data Protection Officer (DPO)");
  lines.push("");
  lines.push(`- **Name:** ${dpoName}`);
  lines.push(`- **Email:** ${dpoEmail}`);
  lines.push("");
  lines.push("**Responsibilities:**");
  lines.push("");
  lines.push("- Monitor compliance with GDPR and other data protection laws");
  lines.push("- Advise on Data Protection Impact Assessments (DPIAs)");
  lines.push("- Act as the point of contact for supervisory authorities");
  lines.push("- Manage data subject access requests (DSARs)");
  lines.push("- Oversee privacy training programme");
  lines.push("- Report to the Privacy Steering Committee");
  lines.push("");

  lines.push("### 5.2 Engineering & Product");
  lines.push("");
  lines.push("- Implement Privacy by Design in all new features");
  lines.push("- Conduct privacy reviews during code review process");
  lines.push("- Maintain data flow documentation");
  lines.push("- Implement technical controls (encryption, access control, logging)");
  if (hasAI) {
    lines.push("- Ensure AI systems comply with transparency and explainability requirements");
  }
  lines.push("");

  lines.push("### 5.3 Legal & Compliance");
  lines.push("");
  lines.push("- Draft and review privacy policies and notices");
  lines.push("- Negotiate DPAs with vendors and customers");
  lines.push("- Monitor regulatory changes and assess impact");
  lines.push("- Support incident response with legal guidance");
  lines.push("");

  lines.push("### 5.4 All Staff");
  lines.push("");
  lines.push("- Complete annual privacy awareness training");
  lines.push("- Report suspected data breaches immediately");
  lines.push("- Follow the data classification and handling policies");
  lines.push("- Escalate privacy concerns to the DPO");
  lines.push("");

  // ── 6. Annual Objectives & Metrics ────────────────────────────────────
  lines.push("## 6. Annual Objectives & Metrics");
  lines.push("");
  lines.push("### 6.1 Objectives");
  lines.push("");
  lines.push("| # | Objective | Target | Owner |");
  lines.push("|---|----------|--------|-------|");
  lines.push(`| 1 | Achieve 100% staff privacy training completion | 100% by Q2 | ${dpoEmail} |`);
  lines.push("| 2 | Complete DPIA for all high-risk processing activities | All identified DPIAs complete | DPO + Engineering |");
  lines.push("| 3 | Review and update all vendor DPAs | Annual renewal cycle | Legal |");
  lines.push("| 4 | Reduce DSAR response time | < 15 business days average | DPO |");
  lines.push("| 5 | Conduct privacy-focused penetration test | 1 per year minimum | CISO |");
  if (hasAI) {
    lines.push("| 6 | Complete AI risk assessments for all AI-powered features | All AI features assessed | Engineering + DPO |");
  }
  lines.push("| 7 | Zero unresolved critical privacy findings | 0 open critical items | Privacy Steering Committee |");
  lines.push("");

  lines.push("### 6.2 Key Performance Indicators (KPIs)");
  lines.push("");
  lines.push("| KPI | Measurement | Target | Frequency |");
  lines.push("|-----|------------|--------|-----------|");
  lines.push("| Training completion rate | % of staff completing annual training | ≥ 95% | Quarterly |");
  lines.push("| DSAR response time | Average days to fulfil DSAR | ≤ 15 days | Monthly |");
  lines.push("| Breach notification time | Hours from detection to authority notification | ≤ 72 hours | Per incident |");
  lines.push("| Vendor compliance rate | % of vendors with current DPAs | 100% | Quarterly |");
  lines.push("| DPIA completion rate | % of high-risk activities with completed DPIA | 100% | Quarterly |");
  lines.push("| Privacy by Design adoption | % of new features with privacy review | ≥ 90% | Monthly |");
  lines.push("| Data minimisation score | Codepliant compliance score | ≥ 80/100 | Per release |");
  if (hasAnalytics) {
    lines.push("| Cookie consent rate | % of users making an active cookie choice | ≥ 70% | Monthly |");
  }
  lines.push("");

  // ── 7. Program Activities ─────────────────────────────────────────────
  lines.push("## 7. Program Activities");
  lines.push("");
  lines.push("### 7.1 Annual Calendar");
  lines.push("");
  lines.push("| Quarter | Activity | Responsible |");
  lines.push("|---------|----------|-------------|");
  lines.push("| Q1 | Annual privacy risk assessment | DPO |");
  lines.push("| Q1 | Update Record of Processing Activities | DPO + Engineering |");
  lines.push("| Q1 | Vendor DPA renewal review | Legal |");
  lines.push("| Q2 | Privacy training campaign launch | DPO + HR |");
  lines.push("| Q2 | Data mapping refresh | Engineering |");
  lines.push("| Q3 | Privacy impact assessment reviews | DPO + Product |");
  lines.push("| Q3 | Penetration test (privacy-focused scope) | CISO |");
  lines.push("| Q4 | Annual privacy program review | Privacy Steering Committee |");
  lines.push("| Q4 | Regulatory landscape review | Legal |");
  lines.push("| Q4 | Board privacy report | DPO |");
  lines.push("| Ongoing | Incident response readiness drills | DPO + Engineering |");
  lines.push("| Ongoing | DSAR handling and tracking | DPO |");
  lines.push("");

  lines.push("### 7.2 Continuous Activities");
  lines.push("");
  lines.push("- **Code scanning:** Run Codepliant on every release to detect changes in data processing");
  lines.push("- **Vendor monitoring:** Track sub-processor changes and assess new vendors");
  lines.push("- **Regulatory monitoring:** Subscribe to supervisory authority updates");
  lines.push("- **Incident response:** Maintain and test the breach response plan");
  if (hasPayment) {
    lines.push("- **PCI compliance:** Maintain PCI DSS compliance for payment processing");
  }
  lines.push("");

  // ── 8. Budget & Resources ─────────────────────────────────────────────
  lines.push("## 8. Budget & Resources");
  lines.push("");
  lines.push("The Privacy Program requires dedicated budget for:");
  lines.push("");
  lines.push("| Category | Items | Estimated Annual Cost |");
  lines.push("|----------|-------|----------------------|");
  lines.push("| **Personnel** | DPO (full-time or fractional), Privacy Champions (% of time) | [To be determined] |");
  lines.push("| **Tools** | Compliance scanning (Codepliant), consent management, DSAR automation | [To be determined] |");
  lines.push("| **Training** | Annual privacy training, specialised DPO training | [To be determined] |");
  lines.push("| **Legal** | External legal counsel, regulatory filings | [To be determined] |");
  lines.push("| **Audit** | Annual privacy audit, penetration testing | [To be determined] |");
  lines.push("| **Insurance** | Cyber liability / data breach insurance | [To be determined] |");
  lines.push("");

  // ── 9. Incident Response Integration ──────────────────────────────────
  lines.push("## 9. Incident Response Integration");
  lines.push("");
  lines.push("The Privacy Program integrates with the Incident Response Plan:");
  lines.push("");
  lines.push("1. **Detection** — Privacy incidents are reported through the same channels as security incidents");
  lines.push("2. **Assessment** — DPO assesses whether a personal data breach has occurred");
  lines.push("3. **Notification** — Authority notification within 72 hours (GDPR Art. 33); data subject notification without undue delay if high risk (GDPR Art. 34)");
  lines.push("4. **Remediation** — Technical fixes, process improvements, updated DPIAs");
  lines.push("5. **Lessons learned** — Post-incident review with Privacy Steering Committee");
  lines.push("");

  // ── 10. Charter Review & Approval ─────────────────────────────────────
  lines.push("## 10. Charter Review & Approval");
  lines.push("");
  lines.push("| Aspect | Detail |");
  lines.push("|--------|--------|");
  lines.push("| **Review frequency** | Annually, or upon significant regulatory changes |");
  lines.push("| **Approval authority** | Privacy Steering Committee + Executive Leadership |");
  lines.push(`| **Charter owner** | ${dpoName} (${dpoEmail}) |`);
  lines.push(`| **Last reviewed** | ${date} |`);
  lines.push(`| **Next review due** | ${new Date(Date.now() + 365 * 86400000).toISOString().split("T")[0]} |`);
  lines.push("");

  // ── 11. Contact ───────────────────────────────────────────────────────
  lines.push("## 11. Contact");
  lines.push("");
  lines.push("For questions about the Privacy Program:");
  lines.push("");
  lines.push(`- **DPO:** ${dpoName} — ${dpoEmail}`);
  lines.push(`- **General Contact:** ${contactEmail}`);
  lines.push(`- **Website:** ${website}`);
  lines.push("");

  // ── Footer ────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Privacy Program Charter was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
    "Customise the objectives, budget, and governance structure to match your organisation. Review with your DPO and executive leadership before adoption.*",
  );
  lines.push("");

  return lines.join("\n");
}
