import type { ScanResult, DetectedService } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates a RISK_REGISTER.md — a catalog of all identified compliance risks
 * with a scoring matrix (likelihood x impact) and mitigation strategies.
 */

interface Risk {
  id: string;
  title: string;
  description: string;
  likelihood: 1 | 2 | 3 | 4 | 5;
  impact: 1 | 2 | 3 | 4 | 5;
  category: "data-breach" | "regulatory" | "vendor" | "operational" | "consent" | "ai-specific";
  mitigations: string[];
  relatedServices: string[];
}

const LIKELIHOOD_LABELS = ["", "Rare", "Unlikely", "Possible", "Likely", "Almost Certain"];
const IMPACT_LABELS = ["", "Negligible", "Minor", "Moderate", "Major", "Critical"];

function riskScore(r: Risk): number {
  return r.likelihood * r.impact;
}

function riskLevel(score: number): string {
  if (score >= 15) return "Critical";
  if (score >= 10) return "High";
  if (score >= 5) return "Medium";
  return "Low";
}

function riskLevelEmoji(score: number): string {
  if (score >= 15) return "🔴";
  if (score >= 10) return "🟠";
  if (score >= 5) return "🟡";
  return "🟢";
}

export function generateRiskRegister(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) {
    return null;
  }

  const company = ctx?.companyName || "[Your Company Name]";
  const date = new Date().toISOString().split("T")[0];
  const jurisdictions = ctx?.jurisdictions || [];

  const risks = identifyRisks(scan, jurisdictions);

  if (risks.length === 0) {
    return null;
  }

  // Sort by score descending
  risks.sort((a, b) => riskScore(b) - riskScore(a));

  const sections: string[] = [];

  // Header
  sections.push(`# Risk Register — ${company}`);
  sections.push("");
  sections.push(`> Auto-generated by Codepliant on ${date}.`);
  sections.push(`> This register catalogs compliance risks identified from code analysis.`);
  sections.push(`> Review with legal and security teams before relying on this for risk management.`);
  sections.push("");

  // Executive summary
  const critical = risks.filter((r) => riskScore(r) >= 15).length;
  const high = risks.filter((r) => riskScore(r) >= 10 && riskScore(r) < 15).length;
  const medium = risks.filter((r) => riskScore(r) >= 5 && riskScore(r) < 10).length;
  const low = risks.filter((r) => riskScore(r) < 5).length;

  sections.push("## Executive Summary");
  sections.push("");
  sections.push(`| Risk Level | Count |`);
  sections.push(`|------------|-------|`);
  if (critical > 0) sections.push(`| 🔴 Critical | ${critical} |`);
  if (high > 0) sections.push(`| 🟠 High | ${high} |`);
  if (medium > 0) sections.push(`| 🟡 Medium | ${medium} |`);
  if (low > 0) sections.push(`| 🟢 Low | ${low} |`);
  sections.push(`| **Total** | **${risks.length}** |`);
  sections.push("");

  // Risk scoring matrix legend
  sections.push("## Risk Scoring Matrix");
  sections.push("");
  sections.push("Risk Score = Likelihood × Impact (1–5 each, max 25)");
  sections.push("");
  sections.push("| Score Range | Level | Action Required |");
  sections.push("|-------------|-------|-----------------|");
  sections.push("| 15–25 | 🔴 Critical | Immediate remediation required |");
  sections.push("| 10–14 | 🟠 High | Address within 30 days |");
  sections.push("| 5–9 | 🟡 Medium | Address within 90 days |");
  sections.push("| 1–4 | 🟢 Low | Monitor and review quarterly |");
  sections.push("");

  // Risk register table
  sections.push("## Risk Register");
  sections.push("");
  sections.push("| ID | Risk | Category | Likelihood | Impact | Score | Level |");
  sections.push("|----|------|----------|------------|--------|-------|-------|");

  for (const risk of risks) {
    const score = riskScore(risk);
    const level = riskLevel(score);
    const emoji = riskLevelEmoji(score);
    sections.push(
      `| ${risk.id} | ${risk.title} | ${risk.category} | ${risk.likelihood} (${LIKELIHOOD_LABELS[risk.likelihood]}) | ${risk.impact} (${IMPACT_LABELS[risk.impact]}) | ${score} | ${emoji} ${level} |`,
    );
  }
  sections.push("");

  // Detailed risk entries
  sections.push("## Risk Details");
  sections.push("");

  for (const risk of risks) {
    const score = riskScore(risk);
    const level = riskLevel(score);
    const emoji = riskLevelEmoji(score);

    sections.push(`### ${risk.id}: ${risk.title} ${emoji}`);
    sections.push("");
    sections.push(`**Category:** ${risk.category}  `);
    sections.push(`**Likelihood:** ${risk.likelihood}/5 (${LIKELIHOOD_LABELS[risk.likelihood]})  `);
    sections.push(`**Impact:** ${risk.impact}/5 (${IMPACT_LABELS[risk.impact]})  `);
    sections.push(`**Risk Score:** ${score}/25 (${level})  `);
    sections.push("");
    sections.push(`**Description:** ${risk.description}`);
    sections.push("");

    if (risk.relatedServices.length > 0) {
      sections.push(`**Related Services:** ${risk.relatedServices.join(", ")}`);
      sections.push("");
    }

    sections.push("**Mitigations:**");
    sections.push("");
    for (const m of risk.mitigations) {
      sections.push(`- [ ] ${m}`);
    }
    sections.push("");
  }

  // Disclaimer
  sections.push("---");
  sections.push("");
  sections.push(
    "*This risk register is generated from automated code analysis and should be reviewed by qualified legal and security professionals. It does not constitute legal advice.*",
  );
  sections.push("");

  return sections.join("\n");
}

// ── Risk identification logic ─────────────────────────────────────────

function identifyRisks(scan: ScanResult, jurisdictions: string[]): Risk[] {
  const risks: Risk[] = [];
  let riskCounter = 0;

  function nextId(): string {
    return `RISK-${String(++riskCounter).padStart(3, "0")}`;
  }

  const services = scan.services;
  const hasAI = services.some((s) => s.category === "ai");
  const hasPayment = services.some((s) => s.category === "payment");
  const hasAnalytics = services.some((s) => s.category === "analytics" || s.category === "advertising");
  const hasAuth = services.some((s) => s.category === "auth");
  const hasDatabase = services.some((s) => s.category === "database");
  const hasEmail = services.some((s) => s.category === "email");
  const thirdPartyCount = services.length;

  // Data breach risks
  if (hasAuth || hasDatabase) {
    risks.push({
      id: nextId(),
      title: "User credentials data breach",
      description: "Authentication or database services store user credentials. A breach could expose passwords, tokens, or personal data.",
      likelihood: 3,
      impact: 5,
      category: "data-breach",
      mitigations: [
        "Implement encryption at rest for all stored credentials",
        "Enable multi-factor authentication",
        "Conduct regular penetration testing",
        "Maintain an incident response plan",
        "Implement rate limiting and account lockout policies",
      ],
      relatedServices: services.filter((s) => s.category === "auth" || s.category === "database").map((s) => s.name),
    });
  }

  if (hasPayment) {
    risks.push({
      id: nextId(),
      title: "Payment data exposure",
      description: "Payment processing services handle sensitive financial data. PCI DSS compliance failures could lead to fines and data exposure.",
      likelihood: 2,
      impact: 5,
      category: "data-breach",
      mitigations: [
        "Verify PCI DSS compliance of all payment processors",
        "Never store raw card numbers — use tokenization",
        "Implement PCI DSS SAQ-A or SAQ-A-EP controls",
        "Conduct annual PCI compliance audits",
        "Use payment processor hosted payment pages where possible",
      ],
      relatedServices: services.filter((s) => s.category === "payment").map((s) => s.name),
    });
  }

  // Regulatory risks
  if (jurisdictions.includes("GDPR") || jurisdictions.length === 0) {
    risks.push({
      id: nextId(),
      title: "GDPR non-compliance",
      description: "Processing personal data of EU residents without full GDPR compliance could result in fines up to 4% of annual global turnover or EUR 20 million.",
      likelihood: hasAnalytics ? 4 : 3,
      impact: 5,
      category: "regulatory",
      mitigations: [
        "Implement lawful basis for each data processing activity",
        "Provide clear and accessible privacy notices",
        "Implement DSAR (Data Subject Access Request) handling procedures",
        "Appoint a Data Protection Officer if required",
        "Maintain a Record of Processing Activities (ROPA)",
        "Implement data minimization practices",
      ],
      relatedServices: services.map((s) => s.name),
    });
  }

  if (jurisdictions.includes("CCPA")) {
    risks.push({
      id: nextId(),
      title: "CCPA non-compliance",
      description: "Processing personal information of California residents without CCPA compliance could result in statutory damages of $100–$750 per consumer per incident.",
      likelihood: hasAnalytics ? 4 : 3,
      impact: 4,
      category: "regulatory",
      mitigations: [
        "Implement 'Do Not Sell My Personal Information' link",
        "Provide opt-out mechanisms for data sharing",
        "Update privacy policy with CCPA-required disclosures",
        "Implement consumer data request handling within 45 days",
        "Train staff on CCPA obligations",
      ],
      relatedServices: services.filter((s) => s.category === "analytics" || s.category === "advertising").map((s) => s.name),
    });
  }

  // Vendor risks
  if (thirdPartyCount >= 3) {
    risks.push({
      id: nextId(),
      title: "Third-party vendor data handling",
      description: `${thirdPartyCount} third-party services detected. Each vendor introduces potential data handling, availability, and compliance risks.`,
      likelihood: 3,
      impact: 3,
      category: "vendor",
      mitigations: [
        "Execute Data Processing Agreements (DPAs) with all vendors",
        "Conduct annual vendor security assessments",
        "Maintain a sub-processor list and notify users of changes",
        "Implement vendor exit strategies and data portability plans",
        "Monitor vendor security posture and incident reports",
      ],
      relatedServices: services.map((s) => s.name),
    });
  }

  // Consent risks
  if (hasAnalytics) {
    risks.push({
      id: nextId(),
      title: "Invalid consent for tracking",
      description: "Analytics and advertising services may collect data before obtaining valid user consent, violating GDPR/ePrivacy requirements.",
      likelihood: 4,
      impact: 4,
      category: "consent",
      mitigations: [
        "Implement a consent management platform (CMP)",
        "Block tracking scripts until consent is obtained",
        "Document and audit consent flows regularly",
        "Provide granular consent options (not just accept/reject)",
        "Implement consent withdrawal mechanisms",
      ],
      relatedServices: services.filter((s) => s.category === "analytics" || s.category === "advertising").map((s) => s.name),
    });
  }

  // AI-specific risks
  if (hasAI) {
    risks.push({
      id: nextId(),
      title: "AI data leakage",
      description: "AI services may process user data through external APIs. Data sent to AI models could be used for training or exposed through model outputs.",
      likelihood: 3,
      impact: 4,
      category: "ai-specific",
      mitigations: [
        "Review AI provider data processing terms and opt out of training",
        "Implement input sanitization before sending data to AI APIs",
        "Log all data sent to and received from AI services",
        "Implement PII detection and redaction before AI processing",
        "Disclose AI usage in privacy policy and terms of service",
      ],
      relatedServices: services.filter((s) => s.category === "ai").map((s) => s.name),
    });

    risks.push({
      id: nextId(),
      title: "EU AI Act non-compliance",
      description: "AI systems may fall under EU AI Act requirements. High-risk AI systems require conformity assessments, registration, and ongoing monitoring.",
      likelihood: 3,
      impact: 4,
      category: "ai-specific",
      mitigations: [
        "Classify AI systems by risk level (minimal/limited/high/unacceptable)",
        "Document AI system purpose, capabilities, and limitations",
        "Implement human oversight mechanisms for high-risk AI",
        "Maintain technical documentation per AI Act Article 11",
        "Register high-risk AI systems in the EU database",
      ],
      relatedServices: services.filter((s) => s.category === "ai").map((s) => s.name),
    });
  }

  // Operational risks
  if (hasEmail) {
    risks.push({
      id: nextId(),
      title: "Unsolicited email communications",
      description: "Email services may be used to send marketing communications without proper consent, violating CAN-SPAM, GDPR, or CASL.",
      likelihood: 3,
      impact: 3,
      category: "operational",
      mitigations: [
        "Implement double opt-in for marketing emails",
        "Include working unsubscribe links in all marketing emails",
        "Maintain suppression lists and honor unsubscribe requests promptly",
        "Separate transactional and marketing email flows",
        "Document lawful basis for each email communication type",
      ],
      relatedServices: services.filter((s) => s.category === "email").map((s) => s.name),
    });
  }

  // Gap-based risks
  const complianceNeeds = scan.complianceNeeds || [];
  const missingDocs = complianceNeeds.filter((n) => n.priority === "required");

  if (missingDocs.length > 0) {
    risks.push({
      id: nextId(),
      title: "Missing required compliance documents",
      description: `${missingDocs.length} required compliance document(s) identified but not yet generated: ${missingDocs.map((n) => n.document).join(", ")}.`,
      likelihood: 5,
      impact: 3,
      category: "regulatory",
      mitigations: [
        "Run 'codepliant go' to generate required documents",
        "Review and customize generated documents with legal counsel",
        "Publish required documents on your website",
        "Set up regular compliance document reviews (quarterly)",
      ],
      relatedServices: [],
    });
  }

  return risks;
}
