import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates SECURITY_AWARENESS_PROGRAM.md — an employee security training program
 * outline covering phishing awareness, password hygiene, incident reporting, and
 * monthly/quarterly activities.
 *
 * Always generated when services are detected (every organization needs security awareness).
 */
export function generateSecurityAwarenessProgram(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const securityEmail = ctx?.securityEmail || contactEmail;
  const dpoName = ctx?.dpoName || "[Data Protection Officer Name]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const date = new Date().toISOString().split("T")[0];
  const year = new Date().getFullYear();

  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasPayment = scan.services.some((s) => s.category === "payment");
  const hasAuth = scan.services.some((s) => s.category === "auth");
  const hasMonitoring = scan.services.some((s) => s.category === "monitoring");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Security Awareness Program");
  lines.push("");
  lines.push(`> **${company}** — Employee Security Training & Awareness Program`);
  lines.push(">");
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(">");
  lines.push("> Generated by [Codepliant](https://github.com/codepliant/codepliant)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Program Overview ─────────────────────────────────────────────────
  lines.push("## 1. Program Overview");
  lines.push("");
  lines.push(
    `${company} is committed to maintaining a strong security posture through continuous employee education. This Security Awareness Program establishes a structured approach to training all personnel on security best practices, threat recognition, and incident response procedures.`,
  );
  lines.push("");
  lines.push("**Program Objectives:**");
  lines.push("");
  lines.push("- Reduce human-factor security incidents by 80%+");
  lines.push("- Achieve 100% staff completion of annual security training");
  lines.push("- Maintain phishing simulation click rates below 5%");
  lines.push("- Ensure all staff can identify and report security incidents");
  lines.push("- Meet compliance requirements (SOC 2, ISO 27001, GDPR Art. 39)");
  lines.push("");

  // ── 2. Scope & Audience ─────────────────────────────────────────────────
  lines.push("## 2. Scope & Audience");
  lines.push("");
  lines.push("| Audience | Training Level | Frequency |");
  lines.push("|----------|---------------|-----------|");
  lines.push("| All employees | Core security awareness | Annual + onboarding |");
  lines.push("| Engineering/DevOps | Secure development practices | Quarterly |");
  lines.push("| Customer support | Social engineering defence | Quarterly |");
  lines.push("| Executive team | Strategic risk awareness | Semi-annually |");
  lines.push("| IT/Security team | Advanced threat response | Monthly |");
  lines.push("| Contractors/vendors | Vendor security requirements | Upon engagement |");
  if (hasAI) {
    lines.push("| AI/ML engineers | AI security & data ethics | Quarterly |");
  }
  if (hasPayment) {
    lines.push("| Finance/billing | PCI DSS & payment security | Annually |");
  }
  lines.push("");

  // ── 3. Core Training Modules ────────────────────────────────────────────
  lines.push("## 3. Core Training Modules");
  lines.push("");

  // 3.1 Phishing
  lines.push("### 3.1 Phishing Awareness");
  lines.push("");
  lines.push("**Duration:** 45 minutes | **Frequency:** Quarterly refresher");
  lines.push("");
  lines.push("#### Learning Objectives");
  lines.push("");
  lines.push("- [ ] Identify common phishing email indicators (sender spoofing, urgency tactics, suspicious links)");
  lines.push("- [ ] Recognise spear-phishing and business email compromise (BEC) attacks");
  lines.push("- [ ] Identify vishing (voice phishing) and smishing (SMS phishing) attempts");
  lines.push("- [ ] Know the correct procedure for reporting suspected phishing");
  lines.push("- [ ] Understand the consequences of successful phishing attacks");
  lines.push("");
  lines.push("#### Key Topics");
  lines.push("");
  lines.push("1. **Email indicators** — hover-over URL inspection, sender verification, header analysis");
  lines.push("2. **Common pretexts** — IT support, CEO fraud, invoice scams, password resets");
  lines.push("3. **Safe behaviour** — never click suspicious links, forward to security team, verify via separate channel");
  lines.push("4. **Real examples** — anonymised examples from industry incidents");
  lines.push("");
  lines.push("#### Phishing Simulation Program");
  lines.push("");
  lines.push("| Metric | Target | Current |");
  lines.push("|--------|--------|---------|");
  lines.push("| Click rate | < 5% | [TBD] |");
  lines.push("| Report rate | > 60% | [TBD] |");
  lines.push("| Simulation frequency | Monthly | |");
  lines.push("| Repeat offender training | Within 48h of click | |");
  lines.push("");

  // 3.2 Password Hygiene
  lines.push("### 3.2 Password Hygiene & Authentication");
  lines.push("");
  lines.push("**Duration:** 30 minutes | **Frequency:** Annually + onboarding");
  lines.push("");
  lines.push("#### Learning Objectives");
  lines.push("");
  lines.push("- [ ] Create strong, unique passwords (16+ characters, passphrase method)");
  lines.push("- [ ] Use a company-approved password manager for all credentials");
  lines.push("- [ ] Enable multi-factor authentication (MFA) on all accounts");
  lines.push("- [ ] Never reuse passwords across services");
  lines.push("- [ ] Recognise and avoid credential stuffing risks");
  lines.push("");
  lines.push("#### Password Policy Summary");
  lines.push("");
  lines.push("| Requirement | Standard |");
  lines.push("|-------------|----------|");
  lines.push("| Minimum length | 16 characters |");
  lines.push("| Complexity | Mix of character types OR passphrase |");
  lines.push("| Rotation | Not required if MFA enabled (NIST 800-63B) |");
  lines.push("| MFA | Required for all corporate accounts |");
  lines.push("| Password manager | Required — company-provided |");
  lines.push("| Shared credentials | Prohibited — use SSO/service accounts |");
  lines.push("");

  // 3.3 Incident Reporting
  lines.push("### 3.3 Incident Reporting");
  lines.push("");
  lines.push("**Duration:** 30 minutes | **Frequency:** Annually + onboarding");
  lines.push("");
  lines.push("#### Learning Objectives");
  lines.push("");
  lines.push("- [ ] Define what constitutes a security incident");
  lines.push("- [ ] Know the internal reporting channels and timelines");
  lines.push("- [ ] Understand that timely reporting is a duty, not optional");
  lines.push("- [ ] Preserve evidence (do not delete emails, logs, screenshots)");
  lines.push("- [ ] Know the escalation path for different incident types");
  lines.push("");
  lines.push("#### Reporting Procedure");
  lines.push("");
  lines.push("```");
  lines.push("1. STOP — Do not attempt to fix the issue yourself");
  lines.push("2. REPORT — Immediately contact:");
  lines.push(`   - Email: ${securityEmail}`);
  lines.push("   - Slack: #security-incidents (if available)");
  lines.push("   - Phone: [Security team phone number]");
  lines.push("3. PRESERVE — Keep all evidence (emails, screenshots, URLs)");
  lines.push("4. DOCUMENT — Note the time, what you observed, and what you did");
  lines.push("5. WAIT — Do not discuss the incident outside the response team");
  lines.push("```");
  lines.push("");

  // 3.4 Social Engineering
  lines.push("### 3.4 Social Engineering Defence");
  lines.push("");
  lines.push("**Duration:** 30 minutes | **Frequency:** Semi-annually");
  lines.push("");
  lines.push("- [ ] Recognise pretexting, baiting, and tailgating techniques");
  lines.push("- [ ] Verify identity before sharing sensitive information");
  lines.push("- [ ] Challenge unknown visitors and report suspicious physical access");
  lines.push("- [ ] Never share credentials, even with \"IT support\"");
  lines.push("- [ ] Use callback verification for financial/sensitive requests");
  lines.push("");

  // 3.5 Device Security
  lines.push("### 3.5 Device & Endpoint Security");
  lines.push("");
  lines.push("**Duration:** 20 minutes | **Frequency:** Annually");
  lines.push("");
  lines.push("- [ ] Lock screens when leaving devices unattended");
  lines.push("- [ ] Enable full-disk encryption on all devices");
  lines.push("- [ ] Keep operating systems and applications up to date");
  lines.push("- [ ] Use only approved software and cloud services");
  lines.push("- [ ] Avoid public Wi-Fi without VPN for work activities");
  lines.push("- [ ] Report lost or stolen devices immediately");
  lines.push("");

  // 3.6 Data Handling
  lines.push("### 3.6 Data Handling & Classification");
  lines.push("");
  lines.push("**Duration:** 30 minutes | **Frequency:** Annually");
  lines.push("");
  lines.push("- [ ] Understand data classification levels (Public, Internal, Confidential, Restricted)");
  lines.push("- [ ] Handle personal data per GDPR/privacy requirements");
  lines.push("- [ ] Use approved channels for sharing sensitive data");
  lines.push("- [ ] Never store sensitive data in unapproved locations (personal email, USB drives)");
  lines.push("- [ ] Apply clean desk policy for physical documents");
  lines.push("");

  // Conditional modules
  if (hasAI) {
    lines.push("### 3.7 AI Security & Data Ethics");
    lines.push("");
    lines.push("**Duration:** 30 minutes | **Frequency:** Quarterly");
    lines.push("");
    lines.push("- [ ] Do not paste confidential data into external AI tools");
    lines.push("- [ ] Understand data retention policies of AI providers");
    lines.push("- [ ] Review AI outputs for sensitive data leakage before sharing");
    lines.push("- [ ] Follow the Acceptable AI Use Policy for approved AI tools");
    lines.push("- [ ] Report AI-generated content that may contain PII or biased outputs");
    lines.push("");
  }

  if (hasPayment) {
    lines.push(`### 3.${hasAI ? "8" : "7"} Payment Card Security (PCI DSS)`);
    lines.push("");
    lines.push("**Duration:** 30 minutes | **Frequency:** Annually");
    lines.push("");
    lines.push("- [ ] Never store full card numbers, CVVs, or PINs");
    lines.push("- [ ] Use only PCI-compliant payment processors");
    lines.push("- [ ] Report any exposure of cardholder data immediately");
    lines.push("- [ ] Follow secure payment handling procedures");
    lines.push("");
  }

  // ── 4. Monthly Activities ───────────────────────────────────────────────
  lines.push("## 4. Monthly Activities");
  lines.push("");
  lines.push(`### ${year} Monthly Calendar`);
  lines.push("");
  lines.push("| Month | Activity | Owner | Status |");
  lines.push("|-------|----------|-------|--------|");
  lines.push("| January | Annual security training kickoff | Security Team | |");
  lines.push("| February | Phishing simulation #1 | Security Team | |");
  lines.push("| March | Password hygiene reminder + MFA audit | IT | |");
  lines.push("| April | Social engineering awareness week | Security Team | |");
  lines.push("| May | Phishing simulation #2 | Security Team | |");
  lines.push("| June | Incident response tabletop exercise | Security + Engineering | |");
  lines.push("| July | Security newsletter: mid-year threats | Security Team | |");
  lines.push("| August | Phishing simulation #3 | Security Team | |");
  lines.push("| September | Clean desk / device security audit | IT | |");
  lines.push("| October | Cybersecurity Awareness Month events | All Teams | |");
  lines.push("| November | Phishing simulation #4 | Security Team | |");
  lines.push("| December | Year-end review + policy update | Security + Legal | |");
  lines.push("");

  // ── 5. Quarterly Activities ─────────────────────────────────────────────
  lines.push("## 5. Quarterly Activities");
  lines.push("");
  lines.push("| Quarter | Activities |");
  lines.push("|---------|-----------|");
  lines.push("| Q1 | Annual training deployment, baseline phishing test, policy review |");
  lines.push("| Q2 | Incident response drill, vendor security review, new hire training audit |");
  lines.push("| Q3 | Advanced threat briefing, access review, compliance check |");
  lines.push("| Q4 | Year-end assessment, program effectiveness review, next-year planning |");
  lines.push("");

  // ── 6. Metrics & KPIs ──────────────────────────────────────────────────
  lines.push("## 6. Metrics & KPIs");
  lines.push("");
  lines.push("| Metric | Target | Measurement Method |");
  lines.push("|--------|--------|--------------------|");
  lines.push("| Training completion rate | 100% within 30 days | LMS tracking |");
  lines.push("| Phishing click rate | < 5% | Simulation platform |");
  lines.push("| Phishing report rate | > 60% | Simulation platform |");
  lines.push("| Mean time to report incidents | < 1 hour | Incident tracker |");
  lines.push("| Security incidents from human error | Decreasing trend | Incident log |");
  lines.push("| Password manager adoption | 100% | IT audit |");
  lines.push("| MFA enrollment | 100% | Identity provider |");
  lines.push("");

  // ── 7. Training Completion Tracking ─────────────────────────────────────
  lines.push("## 7. Training Completion Tracking");
  lines.push("");
  lines.push(`### ${year} Completion Status`);
  lines.push("");
  lines.push("| Department | Enrolled | Completed | Rate | Deadline |");
  lines.push("|------------|----------|-----------|------|----------|");
  lines.push(`| Engineering | | | | ${year}-02-28 |`);
  lines.push(`| Product | | | | ${year}-02-28 |`);
  lines.push(`| Customer Support | | | | ${year}-02-28 |`);
  lines.push(`| Sales/Marketing | | | | ${year}-02-28 |`);
  lines.push(`| Legal/Compliance | | | | ${year}-02-28 |`);
  lines.push(`| Executive Team | | | | ${year}-02-28 |`);
  lines.push(`| **Overall** | | | | ${year}-02-28 |`);
  lines.push("");

  // ── 8. Non-Compliance ──────────────────────────────────────────────────
  lines.push("## 8. Non-Compliance");
  lines.push("");
  lines.push("| Offence | Action |");
  lines.push("|---------|--------|");
  lines.push("| Training not completed by deadline | Manager notified; access restricted until complete |");
  lines.push("| Failed phishing simulation (first time) | Mandatory additional training within 48 hours |");
  lines.push("| Failed phishing simulation (repeat) | One-on-one coaching with security team |");
  lines.push("| Failed phishing simulation (3+ times) | Escalation to management; potential access restriction |");
  lines.push("| Failure to report a security incident | Written warning; potential disciplinary action |");
  lines.push("");

  // ── 9. Program Governance ──────────────────────────────────────────────
  lines.push("## 9. Program Governance");
  lines.push("");
  lines.push("| Role | Responsibility | Contact |");
  lines.push("|------|---------------|---------|");
  lines.push(`| Program Owner | Overall program management | ${securityEmail} |`);
  lines.push(`| DPO | Data protection training oversight | ${dpoName} (${dpoEmail}) |`);
  lines.push("| Department Managers | Ensure team completion | [Department leads] |");
  lines.push("| IT/Security Team | Simulation execution, tool management | [Security team] |");
  lines.push("| HR | Onboarding integration, compliance tracking | [HR team] |");
  lines.push("");

  // ── 10. Tools & Resources ──────────────────────────────────────────────
  lines.push("## 10. Tools & Resources");
  lines.push("");
  lines.push("| Tool | Purpose | Status |");
  lines.push("|------|---------|--------|");
  lines.push("| LMS Platform | Training delivery and tracking | [To configure] |");
  lines.push("| Phishing Simulator | Monthly simulated phishing campaigns | [To configure] |");
  lines.push("| Password Manager | Company-wide credential management | [To deploy] |");
  lines.push("| Security Newsletter | Monthly threat intelligence digest | [To set up] |");
  lines.push("");
  lines.push("### Related Documents");
  lines.push("");
  lines.push("- Incident Response Plan (`INCIDENT_RESPONSE_PLAN.md`)");
  lines.push("- Access Control Policy (`ACCESS_CONTROL_POLICY.md`)");
  lines.push("- Information Security Policy (`INFORMATION_SECURITY_POLICY.md`)");
  lines.push("- Training Record (`TRAINING_RECORD.md`)");
  if (hasAI) {
    lines.push("- Acceptable AI Use Policy (`ACCEPTABLE_AI_USE_POLICY.md`)");
  }
  lines.push("");

  // ── Footer ─────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Security Awareness Program was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
    "Customise the training topics, schedule, and metrics to match your organisation's specific needs. Review with your security team and legal counsel before implementation.*",
  );
  lines.push("");

  return lines.join("\n");
}
