import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates THIRD_PARTY_DUE_DILIGENCE_TEMPLATE.md — a questionnaire template
 * for evaluating new vendors before onboarding.
 *
 * Includes:
 * - Security assessment questions
 * - Privacy and data protection questions
 * - Compliance and regulatory questions
 * - Scoring rubric with pass/fail thresholds
 *
 * Pre-populated with context from detected services and categories.
 *
 * Returns null when no services are detected.
 */
export function generateThirdPartyDueDiligence(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const date = new Date().toISOString().split("T")[0];

  const jurisdiction = ctx?.jurisdiction || "";
  const jurisdictions = ctx?.jurisdictions || [];
  const allJurisdictions = new Set<string>();
  if (jurisdiction) allJurisdictions.add(jurisdiction);
  for (const j of jurisdictions) allJurisdictions.add(j);

  const hasEU = allJurisdictions.has("EU") || allJurisdictions.has("UK");
  const hasUS = allJurisdictions.has("US") || allJurisdictions.has("CCPA");
  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasPayment = scan.services.some((s) => s.category === "payment");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Third-Party Due Diligence Template");
  lines.push("");
  lines.push(`> **${company}** — Vendor Evaluation Questionnaire`);
  lines.push(">");
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(">");
  lines.push("> Generated by [Codepliant](https://github.com/codepliant/codepliant)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Purpose ──────────────────────────────────────────────────────────
  lines.push("## 1. Purpose");
  lines.push("");
  lines.push(
    `This questionnaire is used by ${company} to evaluate the security, privacy, and compliance posture of prospective vendors and sub-processors before onboarding. All vendors that will process personal data on behalf of ${company} must complete this assessment.`,
  );
  lines.push("");
  lines.push("**When to use this template:**");
  lines.push("");
  lines.push("- Evaluating a new SaaS vendor or sub-processor");
  lines.push("- Renewing an existing vendor relationship (annually)");
  lines.push("- Vendor undergoes a material change (acquisition, breach, new data processing)");
  lines.push("- Adding a new integration that processes personal data");
  lines.push("");

  // ── 2. Vendor Information ──────────────────────────────────────────────
  lines.push("## 2. Vendor Information");
  lines.push("");
  lines.push("| Field | Response |");
  lines.push("|-------|----------|");
  lines.push("| **Vendor name** | |");
  lines.push("| **Vendor website** | |");
  lines.push("| **Primary contact name** | |");
  lines.push("| **Primary contact email** | |");
  lines.push("| **Service description** | |");
  lines.push("| **Data processing location(s)** | |");
  lines.push("| **Contract start date** | |");
  lines.push("| **Assessment completed by** | |");
  lines.push("| **Assessment date** | |");
  lines.push("");

  // ── 3. Data Classification ────────────────────────────────────────────
  lines.push("## 3. Data Classification");
  lines.push("");
  lines.push("Identify what data the vendor will access or process:");
  lines.push("");
  lines.push("| Data Category | Yes/No | Details |");
  lines.push("|--------------|--------|---------|");
  lines.push("| Personal identifiers (name, email, phone) | | |");
  lines.push("| Financial data (payment, billing) | | |");
  lines.push("| Authentication credentials | | |");
  lines.push("| Health data | | |");
  lines.push("| Biometric data | | |");
  lines.push("| Location data | | |");
  lines.push("| Behavioural / usage analytics | | |");
  lines.push("| Children's data (under 16) | | |");
  if (hasAI) {
    lines.push("| AI training data | | |");
    lines.push("| AI model outputs / inferences | | |");
  }
  lines.push("| Employee data | | |");
  lines.push("| Other (describe) | | |");
  lines.push("");

  // ── 4. Security Assessment ────────────────────────────────────────────
  lines.push("## 4. Security Assessment");
  lines.push("");
  lines.push("### 4.1 Infrastructure & Architecture");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| S1 | Do you encrypt data at rest? (Specify algorithm) | | |");
  lines.push("| S2 | Do you encrypt data in transit? (TLS 1.2+ minimum) | | |");
  lines.push("| S3 | Do you support customer-managed encryption keys (CMEK)? | | |");
  lines.push("| S4 | Where is data stored? List all regions/data centres. | | |");
  lines.push("| S5 | Do you maintain network segmentation between tenants? | | |");
  lines.push("| S6 | Do you use a Web Application Firewall (WAF)? | | |");
  lines.push("| S7 | Do you have DDoS protection in place? | | |");
  lines.push("");

  lines.push("### 4.2 Access Control");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| S8 | Do you enforce multi-factor authentication (MFA) for all staff? | | |");
  lines.push("| S9 | Do you implement role-based access control (RBAC)? | | |");
  lines.push("| S10 | How are privileged access accounts managed? | | |");
  lines.push("| S11 | Do you perform periodic access reviews? (Frequency?) | | |");
  lines.push("| S12 | Do you have an automated offboarding process for revoked access? | | |");
  lines.push("");

  lines.push("### 4.3 Incident Response");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| S13 | Do you have a documented incident response plan? | | |");
  lines.push("| S14 | What is your breach notification timeline? (Hours) | | |");
  lines.push("| S15 | Have you had a data breach in the last 24 months? | | |");
  lines.push("| S16 | Do you conduct incident response drills? (Frequency?) | | |");
  lines.push("| S17 | Do you have cyber insurance? | | |");
  lines.push("");

  lines.push("### 4.4 Vulnerability Management");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| S18 | Do you perform regular penetration testing? (Frequency?) | | |");
  lines.push("| S19 | Do you have a vulnerability disclosure programme? | | |");
  lines.push("| S20 | What is your patch management SLA for critical vulnerabilities? | | |");
  lines.push("| S21 | Do you perform static/dynamic application security testing (SAST/DAST)? | | |");
  lines.push("");

  // ── 5. Privacy Assessment ────────────────────────────────────────────
  lines.push("## 5. Privacy Assessment");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| P1 | Do you have a published privacy policy? (Provide URL) | | |");
  lines.push("| P2 | Do you process data only as instructed by the controller? | | |");
  lines.push("| P3 | Can you support data subject access requests (DSARs)? | | |");
  lines.push("| P4 | Can you support data deletion requests? (Timeline?) | | |");
  lines.push("| P5 | Can you export data in a portable format? (Which formats?) | | |");
  lines.push("| P6 | Do you use sub-processors? (List them) | | |");
  lines.push("| P7 | Do you notify customers before adding/changing sub-processors? | | |");
  lines.push("| P8 | Do you conduct Data Protection Impact Assessments (DPIAs)? | | |");
  lines.push("| P9 | Do you have a Data Protection Officer (DPO)? (Contact details) | | |");
  lines.push("| P10 | What is your data retention policy? | | |");
  lines.push("| P11 | Do you anonymise or pseudonymise personal data? | | |");
  if (hasAI) {
    lines.push("| P12 | Do you use customer data for AI model training? (Opt-out available?) | | |");
    lines.push("| P13 | Do you provide transparency reports for automated decision-making? | | |");
  }
  lines.push("");

  // ── 6. Compliance Assessment ──────────────────────────────────────────
  lines.push("## 6. Compliance Assessment");
  lines.push("");
  lines.push("### 6.1 Certifications & Attestations");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| C1 | Do you hold SOC 2 Type II certification? (Date of last report) | | |");
  lines.push("| C2 | Do you hold ISO 27001 certification? (Certificate number) | | |");
  if (hasEU) {
    lines.push("| C3 | Are you GDPR compliant? (Provide evidence) | | |");
  }
  if (hasUS) {
    lines.push("| C4 | Are you CCPA/CPRA compliant? | | |");
  }
  if (hasPayment) {
    lines.push("| C5 | Do you hold PCI DSS certification? (Level?) | | |");
  }
  lines.push("| C6 | Do you have a HIPAA BAA available (if applicable)? | | |");
  lines.push("| C7 | Are audit reports available to customers upon request? | | |");
  lines.push("");

  lines.push("### 6.2 Contractual");
  lines.push("");
  lines.push("| # | Question | Response | Score (0-3) |");
  lines.push("|---|----------|----------|-------------|");
  lines.push("| C8 | Can you sign a Data Processing Agreement (DPA)? | | |");
  lines.push("| C9 | Can you agree to Standard Contractual Clauses (SCCs) for international transfers? | | |");
  lines.push("| C10 | Do you offer data processing addendums for specific jurisdictions? | | |");
  lines.push("| C11 | What is your liability cap for data breaches? | | |");
  lines.push("| C12 | Do you have a business continuity / disaster recovery plan? | | |");
  lines.push("| C13 | What are your SLA commitments? (Uptime, support response time) | | |");
  lines.push("");

  // ── 7. Scoring Rubric ────────────────────────────────────────────────
  lines.push("## 7. Scoring Rubric");
  lines.push("");
  lines.push("### 7.1 Score Definitions");
  lines.push("");
  lines.push("| Score | Meaning | Description |");
  lines.push("|-------|---------|-------------|");
  lines.push("| **0** | Not implemented | No capability or evidence exists |");
  lines.push("| **1** | Partial | Some measures exist but are incomplete or informal |");
  lines.push("| **2** | Implemented | Measures are in place and documented |");
  lines.push("| **3** | Mature | Measures are in place, documented, audited, and continuously improved |");
  lines.push("");

  lines.push("### 7.2 Scoring Thresholds");
  lines.push("");

  // Count total questions
  let totalQuestions = 21 + 11 + 13; // S(21) + P(11) + C(13)
  if (hasAI) totalQuestions += 2 + 2; // P12,P13 + AI compliance
  if (hasEU) totalQuestions += 1;
  if (hasUS) totalQuestions += 1;
  if (hasPayment) totalQuestions += 1;

  const maxScore = totalQuestions * 3;

  lines.push("| Category | Questions | Max Score |");
  lines.push("|----------|-----------|-----------|");
  lines.push(`| Security (S1-S21) | 21 | 63 |`);
  lines.push(`| Privacy (P1-P${hasAI ? "13" : "11"}) | ${hasAI ? 13 : 11} | ${(hasAI ? 13 : 11) * 3} |`);

  let complianceCount = 13;
  if (hasEU) complianceCount++;
  if (hasUS) complianceCount++;
  if (hasPayment) complianceCount++;

  lines.push(`| Compliance (C1-C${complianceCount}) | ${complianceCount} | ${complianceCount * 3} |`);
  lines.push(`| **Total** | **${totalQuestions}** | **${maxScore}** |`);
  lines.push("");

  lines.push("### 7.3 Risk Classification");
  lines.push("");
  lines.push("| Overall Score (%) | Risk Level | Decision |");
  lines.push("|-------------------|------------|----------|");
  lines.push("| ≥ 85% | **Low Risk** | Approved — standard DPA required |");
  lines.push("| 70-84% | **Medium Risk** | Conditional approval — remediation plan required within 90 days |");
  lines.push("| 50-69% | **High Risk** | Escalate to Privacy Steering Committee — additional controls required |");
  lines.push("| < 50% | **Critical Risk** | **Do not proceed** — vendor does not meet minimum requirements |");
  lines.push("");

  lines.push("### 7.4 Mandatory Requirements (Hard Fails)");
  lines.push("");
  lines.push("The following are non-negotiable. A score of 0 on any of these results in automatic rejection:");
  lines.push("");
  lines.push("- **S1** — Data must be encrypted at rest");
  lines.push("- **S2** — Data must be encrypted in transit (TLS 1.2+)");
  lines.push("- **S13** — Must have a documented incident response plan");
  lines.push("- **S14** — Breach notification within 72 hours");
  lines.push("- **P2** — Must process data only as instructed");
  lines.push("- **C8** — Must sign a DPA");
  lines.push("");

  // ── 8. Assessment Workflow ────────────────────────────────────────────
  lines.push("## 8. Assessment Workflow");
  lines.push("");
  lines.push("```");
  lines.push("1. Business owner submits vendor request");
  lines.push("     ↓");
  lines.push("2. DPO sends this questionnaire to vendor");
  lines.push("     ↓");
  lines.push("3. Vendor completes and returns with evidence");
  lines.push("     ↓");
  lines.push("4. DPO scores responses and classifies risk");
  lines.push("     ↓");
  lines.push("5a. Low/Medium Risk → DPO approves (with conditions if medium)");
  lines.push("5b. High Risk → Privacy Steering Committee review");
  lines.push("5c. Critical Risk → Rejected");
  lines.push("     ↓");
  lines.push("6. DPA executed, vendor added to sub-processor list");
  lines.push("     ↓");
  lines.push("7. Annual reassessment scheduled");
  lines.push("```");
  lines.push("");

  // ── 9. Assessment Summary ─────────────────────────────────────────────
  lines.push("## 9. Assessment Summary");
  lines.push("");
  lines.push("*To be completed by the assessor:*");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|-------|-------|");
  lines.push("| **Vendor name** | |");
  lines.push("| **Total score** | /  |");
  lines.push("| **Percentage** | % |");
  lines.push("| **Risk level** | Low / Medium / High / Critical |");
  lines.push("| **Hard fail triggers** | None / List items |");
  lines.push("| **Decision** | Approved / Conditional / Escalated / Rejected |");
  lines.push("| **Conditions (if any)** | |");
  lines.push("| **Assessed by** | |");
  lines.push("| **Assessment date** | |");
  lines.push("| **Next review date** | |");
  lines.push("");

  // ── 10. Contact ───────────────────────────────────────────────────────
  lines.push("## 10. Contact");
  lines.push("");
  lines.push("For questions about vendor due diligence:");
  lines.push("");
  lines.push(`- **DPO:** ${dpoEmail}`);
  lines.push(`- **General Contact:** ${contactEmail}`);
  lines.push("");

  // ── Footer ────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Third-Party Due Diligence Template was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
    "Customise the questions and scoring thresholds to match your risk appetite. Review with your DPO and legal counsel before use.*",
  );
  lines.push("");

  return lines.join("\n");
}
