import type { ScanResult } from "../scanner/index.js";
import type { GeneratorContext } from "./index.js";

/**
 * Generates TRAINING_RECORD.md — a GDPR Art. 39(1)(b) staff training record
 * template covering data protection basics, breach procedures, and DSAR handling.
 *
 * Always generated when services are detected (every organization processing
 * personal data needs staff awareness training records).
 */
export function generateTrainingRecord(
  scan: ScanResult,
  ctx?: GeneratorContext,
): string | null {
  if (scan.services.length === 0) return null;

  const company = ctx?.companyName || "[Your Company Name]";
  const contactEmail = ctx?.contactEmail || "[your-email@example.com]";
  const dpoName = ctx?.dpoName || "[Data Protection Officer Name]";
  const dpoEmail = ctx?.dpoEmail || contactEmail;
  const date = new Date().toISOString().split("T")[0];

  const hasAI = scan.services.some((s) => s.category === "ai");
  const hasPayment = scan.services.some((s) => s.category === "payment");
  const hasAnalytics = scan.services.some((s) => s.category === "analytics");
  const hasAuth = scan.services.some((s) => s.category === "auth");

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────
  lines.push("# Staff Data Protection Training Record");
  lines.push("");
  lines.push(`> **${company}** — GDPR Art. 39(1)(b) Training Record`);
  lines.push(">");
  lines.push(`> **Effective Date:** ${date}`);
  lines.push(">");
  lines.push("> Generated by [Codepliant](https://github.com/codepliant/codepliant)");
  lines.push("");
  lines.push("---");
  lines.push("");

  // ── 1. Purpose ──────────────────────────────────────────────────────────
  lines.push("## 1. Purpose");
  lines.push("");
  lines.push(
    `This document records staff training on data protection matters as required by GDPR Article 39(1)(b). ${company} is committed to ensuring all personnel who process personal data understand their obligations under applicable data protection laws.`,
  );
  lines.push("");
  lines.push("**Legal Basis:** Under GDPR Art. 39(1)(b), the Data Protection Officer is tasked with monitoring compliance, including \"the assignment of responsibilities, awareness-raising and training of staff involved in processing operations, and the related audits.\"");
  lines.push("");

  // ── 2. Training Schedule ────────────────────────────────────────────────
  lines.push("## 2. Training Schedule");
  lines.push("");
  lines.push("| Training Type | Frequency | Target Audience | Duration |");
  lines.push("|---------------|-----------|-----------------|----------|");
  lines.push("| Onboarding Training | Within first week of employment | All new staff | 2 hours |");
  lines.push("| Annual Refresher | Annually (Q1) | All staff | 1.5 hours |");
  lines.push("| Breach Response Drill | Bi-annually (Q2, Q4) | Incident response team | 1 hour |");
  lines.push("| DSAR Handling | Annually (Q1) | Customer support, legal, engineering | 1 hour |");
  if (hasAI) {
    lines.push("| AI & Data Ethics | Annually (Q2) | Engineering, product, AI/ML teams | 1.5 hours |");
  }
  if (hasPayment) {
    lines.push("| Payment Data Handling (PCI DSS) | Annually (Q1) | Finance, engineering, support | 1 hour |");
  }
  lines.push("| Role-Specific Deep Dive | As needed | Specialist teams | 1-2 hours |");
  lines.push("");

  // ── 3. Core Training Topics ─────────────────────────────────────────────
  lines.push("## 3. Core Training Topics");
  lines.push("");

  lines.push("### 3.1 Data Protection Basics");
  lines.push("");
  lines.push("- [ ] What constitutes personal data and special category data");
  lines.push("- [ ] The six GDPR principles (lawfulness, fairness, transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity & confidentiality, accountability)");
  lines.push("- [ ] Lawful bases for processing (consent, contract, legal obligation, vital interests, public task, legitimate interests)");
  lines.push("- [ ] Data subject rights overview (access, rectification, erasure, restriction, portability, objection)");
  lines.push("- [ ] Privacy by design and by default (Art. 25)");
  lines.push("- [ ] International data transfers and safeguards");
  lines.push(`- [ ] ${company}'s role as data controller/processor`);
  lines.push("");

  lines.push("### 3.2 Breach Procedures");
  lines.push("");
  lines.push("- [ ] Definition of a personal data breach");
  lines.push("- [ ] How to recognise a potential breach");
  lines.push("- [ ] Internal escalation procedure (report within 4 hours to DPO)");
  lines.push("- [ ] 72-hour supervisory authority notification requirement (Art. 33)");
  lines.push("- [ ] Data subject notification requirements (Art. 34)");
  lines.push("- [ ] Breach documentation and record-keeping");
  lines.push("- [ ] Post-breach review and lessons learned");
  lines.push("");

  lines.push("### 3.3 DSAR Handling");
  lines.push("");
  lines.push("- [ ] Recognising a Data Subject Access Request (verbal and written)");
  lines.push("- [ ] Identity verification procedures");
  lines.push("- [ ] Response timeline (1 month, extendable to 3 months for complex requests)");
  lines.push("- [ ] Information to include in responses");
  lines.push("- [ ] Handling requests for erasure, rectification, and restriction");
  lines.push("- [ ] When and how to refuse a request (manifestly unfounded or excessive)");
  lines.push("- [ ] Escalation to the DPO");
  lines.push("");

  // ── 3.4 Role-specific topics ────────────────────────────────────────────
  const roleSpecificTopics: string[] = [];

  if (hasAI) {
    roleSpecificTopics.push("### 3.4 AI & Automated Decision-Making");
    roleSpecificTopics.push("");
    roleSpecificTopics.push("- [ ] Transparency obligations for AI systems (Art. 22)");
    roleSpecificTopics.push("- [ ] Right to human intervention in automated decisions");
    roleSpecificTopics.push("- [ ] AI training data privacy considerations");
    roleSpecificTopics.push("- [ ] Bias detection and fairness requirements");
    roleSpecificTopics.push("- [ ] EU AI Act risk classification awareness");
    roleSpecificTopics.push("");
  }

  if (hasPayment) {
    roleSpecificTopics.push("### 3.5 Payment Data Protection");
    roleSpecificTopics.push("");
    roleSpecificTopics.push("- [ ] PCI DSS fundamentals and cardholder data handling");
    roleSpecificTopics.push("- [ ] Tokenisation and encryption requirements");
    roleSpecificTopics.push("- [ ] Secure payment processing procedures");
    roleSpecificTopics.push("- [ ] Incident handling for payment data breaches");
    roleSpecificTopics.push("");
  }

  if (hasAnalytics) {
    roleSpecificTopics.push("### 3.6 Analytics & Tracking");
    roleSpecificTopics.push("");
    roleSpecificTopics.push("- [ ] Cookie consent requirements (ePrivacy Directive)");
    roleSpecificTopics.push("- [ ] Anonymisation vs pseudonymisation of analytics data");
    roleSpecificTopics.push("- [ ] Data minimisation in analytics collection");
    roleSpecificTopics.push("- [ ] Third-party analytics provider obligations");
    roleSpecificTopics.push("");
  }

  if (hasAuth) {
    roleSpecificTopics.push("### 3.7 Authentication & Access Data");
    roleSpecificTopics.push("");
    roleSpecificTopics.push("- [ ] Secure credential storage and handling");
    roleSpecificTopics.push("- [ ] Session data and privacy implications");
    roleSpecificTopics.push("- [ ] Multi-factor authentication best practices");
    roleSpecificTopics.push("- [ ] Logging and audit trail privacy requirements");
    roleSpecificTopics.push("");
  }

  if (roleSpecificTopics.length > 0) {
    lines.push(...roleSpecificTopics);
  }

  // ── 4. Sign-Off Sheet ──────────────────────────────────────────────────
  lines.push("## 4. Training Sign-Off Sheet");
  lines.push("");
  lines.push("Each staff member must sign off after completing each training module.");
  lines.push("");
  lines.push("| # | Employee Name | Role/Department | Training Module | Date Completed | Trainer | Signature |");
  lines.push("|---|---------------|-----------------|-----------------|----------------|---------|-----------|");
  lines.push("| 1 | | | Data Protection Basics | | | |");
  lines.push("| 2 | | | Breach Procedures | | | |");
  lines.push("| 3 | | | DSAR Handling | | | |");
  lines.push("| 4 | | | Annual Refresher | | | |");
  lines.push("| 5 | | | | | | |");
  lines.push("| 6 | | | | | | |");
  lines.push("| 7 | | | | | | |");
  lines.push("| 8 | | | | | | |");
  lines.push("");

  // ── 5. Training Completion Tracker ─────────────────────────────────────
  lines.push("## 5. Annual Training Completion Tracker");
  lines.push("");
  const year = new Date().getFullYear();
  lines.push(`### ${year} Training Year`);
  lines.push("");
  lines.push("| Department | Total Staff | Completed | Completion Rate | Deadline |");
  lines.push("|------------|-------------|-----------|-----------------|----------|");
  lines.push(`| Engineering | | | | ${year}-03-31 |`);
  lines.push(`| Product | | | | ${year}-03-31 |`);
  lines.push(`| Customer Support | | | | ${year}-03-31 |`);
  lines.push(`| Legal/Compliance | | | | ${year}-03-31 |`);
  lines.push(`| Marketing | | | | ${year}-03-31 |`);
  lines.push(`| HR/People Ops | | | | ${year}-03-31 |`);
  lines.push(`| Executive Team | | | | ${year}-03-31 |`);
  lines.push(`| **Overall** | | | | ${year}-03-31 |`);
  lines.push("");

  // ── 6. Training Materials & Resources ──────────────────────────────────
  lines.push("## 6. Training Materials & Resources");
  lines.push("");
  lines.push("| Resource | Location | Last Updated |");
  lines.push("|----------|----------|--------------|");
  lines.push("| Data Protection Handbook | [Internal link] | |");
  lines.push("| Breach Response Playbook | `INCIDENT_RESPONSE_PLAN.md` | |");
  lines.push("| DSAR Process Guide | `DSAR_HANDLING_GUIDE.md` | |");
  lines.push("| Privacy Policy | `PRIVACY_POLICY.md` | |");
  lines.push("| Data Protection Policy | `DATA_PROTECTION_POLICY.md` | |");
  lines.push("| DPO Handbook | `DPO_HANDBOOK.md` | |");
  lines.push("");

  // ── 7. Assessment & Certification ──────────────────────────────────────
  lines.push("## 7. Assessment & Certification");
  lines.push("");
  lines.push("### Post-Training Assessment");
  lines.push("");
  lines.push("Each training module concludes with a short assessment:");
  lines.push("");
  lines.push("- **Passing score:** 80% or higher");
  lines.push("- **Retake policy:** Staff who do not pass may retake after 7 days");
  lines.push("- **Records retention:** Assessment results retained for 3 years");
  lines.push("");
  lines.push("### Certification");
  lines.push("");
  lines.push("| Field | Details |");
  lines.push("|-------|---------|");
  lines.push(`| **Training Coordinator** | ${dpoName} |`);
  lines.push(`| **Contact** | ${dpoEmail} |`);
  lines.push(`| **Organisation** | ${company} |`);
  lines.push(`| **Record Created** | ${date} |`);
  lines.push("| **Next Review Date** | [12 months from creation] |");
  lines.push("");

  // ── 8. Non-Compliance ──────────────────────────────────────────────────
  lines.push("## 8. Non-Compliance");
  lines.push("");
  lines.push("Failure to complete mandatory data protection training may result in:");
  lines.push("");
  lines.push("1. Temporary suspension of access to systems containing personal data");
  lines.push("2. Formal written warning");
  lines.push("3. Disciplinary action in accordance with company policy");
  lines.push("");
  lines.push(`Managers are responsible for ensuring their team members complete training on schedule. The DPO (${dpoEmail}) will provide monthly compliance reports to department heads.`);
  lines.push("");

  // ── Footer ─────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*This Training Record was auto-generated by [Codepliant](https://github.com/codepliant/codepliant) based on code analysis. " +
    "Customise the training topics and schedule to match your organisation's specific data processing activities. Review with your DPO and legal counsel before use.*",
  );
  lines.push("");

  return lines.join("\n");
}
